import React from 'react';
import {interpolate,Easing} from 'remotion';
import {Surface,Txt,q,mix} from './UI';
export const accent='#cfb9f7';
// C02/C05 original library-v2 motion curve, adapted to current narration and safe canvas.
export const progress=(t:number,start:number,duration:number)=>interpolate(t,[start,start+duration],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.bezier(.2,.8,.2,1)});
export const typed=(s:string,t:number,start:number,duration=.4)=>s.slice(0,Math.floor(Math.max(0,Math.min(1,(t-start)/duration))*s.length));
export function TitleWindow({x=320,y=140,w=1280,h=720,children,style={}}:any){return <Surface x={x} y={y} w={w} h={h} style={{background:'#202529',color:'#fff',borderRadius:28,boxShadow:'12px 18px 28px #0003',...style}}><div style={{height:62,background:'#111719',display:'flex',gap:16,padding:'21px 28px'}}>{['#b85b91','#ddb654','#6598b3'].map(c=><i key={c} style={{width:20,height:20,borderRadius:24,background:c}}/>)}</div>{children}</Surface>}
export function Pill({text,x,y,w=600,h=150,size=66,color='#fff',scale=1,style={}}:any){return <Surface x={x-w/2} y={y-h/2} w={w} h={h} dark style={{borderRadius:Math.min(h*.32,45),display:'grid',placeItems:'center',transform:`scale(${scale})`,boxShadow:'8px 12px 20px #0002',...style}}><span style={{fontWeight:600,fontSize:size,color,whiteSpace:'pre',lineHeight:1.2,textAlign:'center'}}>{text}</span></Surface>}
export function Path({d,p=1,width=6,color='#111'}:any){if(p<=0)return null;return <path d={d} pathLength={1} stroke={color} fill="none" strokeWidth={width} strokeLinecap="round" strokeLinejoin="round" strokeDasharray={1} strokeDashoffset={1-p}/>}
export function Person({x,y,label='',size=96,active=false}:any){return <div style={{position:'absolute',left:x-size/2,top:y-size/2,width:size,textAlign:'center'}}><svg width={size} height={size} viewBox="0 0 100 100"><circle cx="50" cy="50" r="47" fill={active?'#111':'#fff'} stroke="#111" strokeWidth="3"/><circle cx="50" cy="36" r="14" fill={active?'#fff':'#111'}/><path d="M24 76 Q24 54 50 54 Q76 54 76 76Z" fill={active?'#fff':'#111'}/></svg>{label&&<div style={{position:'absolute',top:size+16,left:-100,width:size+200,fontSize:36,fontWeight:600,whiteSpace:'nowrap'}}>{label}</div>}</div>}
export function Document({x,y,w=620,h=400,title='',kind='document',active=0,style={}}:any){
 return <Surface x={x} y={y} w={w} h={h} style={{borderRadius:22,boxShadow:'0 12px 35px #0002',...style}}><Txt x={w*.08} y={h*.09} w={w*.84} size={Math.min(52,w*.078)}>{title}</Txt><div style={{position:'absolute',left:w*.08,right:w*.08,top:h*.3,bottom:h*.08}}>{kind==='table'?<div style={{height:'100%',display:'grid',gridTemplateColumns:'1.4fr 1fr 1fr',gridTemplateRows:'repeat(4,1fr)',gap:3,background:'#ddd',padding:3}}>{Array.from({length:12},(_,i)=><div key={i} style={{background:i<3?'#17191c':i===4&&active>0?accent:'#f8f8f8',display:'flex',alignItems:'center',padding:'0 10%'}}><div style={{height:6,width:i%3? '48%':'73%',background:i<3?'#aaa':'#bdc0c4',borderRadius:4}}/></div>)}</div>:kind==='task'?<div style={{display:'grid',gap:18}}>{[0,1,2].map(i=><div key={i} style={{display:'flex',gap:20,alignItems:'center'}}><div style={{width:26,height:26,border:'3px solid #111',borderRadius:5,background:active>i/3?'#111':'white'}}/><div style={{width:(70-i*10)+'%',height:12,background:'#c9cbd0',borderRadius:6}}/></div>)}</div>:<>{[.87,.68,.92,.53].map((v,i)=><div key={i} style={{height:12,marginBottom:25,width:v*100+'%',background:i===1&&active>0?accent:'#d1d3d5',borderRadius:4}}/>)}</>}</div></Surface>;
}
// Original PermissionOrbit point-at-length geometry, scaled uniformly from 3840x2160.
function pointAt(p:number){const r=340,straight=860,arc=Math.PI*r,d=Math.max(0,Math.min(1,p))*2*(arc+straight);let x,y;if(d<=arc){const a=Math.PI/2-d/r;x=1390+r*Math.cos(a);y=525+r*Math.sin(a);}else if(d<=arc+straight){x=1390-(d-arc);y=185;}else if(d<=2*arc+straight){const a=-Math.PI/2-(d-arc-straight)/r;x=530+r*Math.cos(a);y=525+r*Math.sin(a);}else{x=530+d-2*arc-straight;y=865;}return {x,y};}
const orbitPath=Array.from({length:241},(_,i)=>{const p=pointAt(i/240);return `${i?'L':'M'}${p.x},${p.y}`}).join(' ');
export function PermissionOrbit({p}:any){const point=pointAt(p);return <svg width={1920} height={1080} style={{position:'absolute',inset:0}}><Path d={orbitPath} p={p} color="#a5a8ab" width={4}/>{p>0&&<circle cx={point.x} cy={point.y} r={28} fill="#111" stroke="#fff" strokeWidth={4}/>}</svg>}
export function Cursor({x,y,label}:any){return <div style={{position:'absolute',left:x,top:y}}><svg width="54" height="66" viewBox="0 0 54 66"><path d="M4 3L4 51L18 39L28 61L39 56L29 35L49 35Z" fill="#111" stroke="white" strokeWidth="3"/></svg><div style={{position:'absolute',left:37,top:42,background:'#111',color:'white',padding:'7px 14px',borderRadius:8,fontSize:23,whiteSpace:'nowrap'}}>{label}</div></div>}
