import React from 'react';
import {Img,staticFile,interpolate,Easing} from 'remotion';
// Adapted from ep93 part1-v3 UI.tsx: same easing, surfaces and text handoff.
export const q=(t:number,a:number,b:number)=>interpolate(t,[a,b],[0,1],{easing:Easing.bezier(.16,1,.3,1),extrapolateLeft:'clamp',extrapolateRight:'clamp'});
export const mix=(a:number,b:number,p:number)=>a+(b-a)*p;
export const Txt=({x=0,y=0,w=1920,size=72,children,style={}}:any)=><div data-content style={{position:'absolute',left:x,top:y,width:w,fontSize:size,fontWeight:600,lineHeight:1.3,...style}}>{children}</div>;
export const Surface=({x=0,y=0,w=1000,h=600,dark=false,children,style={}}:any)=><div style={{position:'absolute',left:x,top:y,width:w,height:h,background:dark?'#111':'#fff',color:dark?'#fff':'#111',borderRadius:26,overflow:'hidden',boxShadow:'0 20px 60px #00000016',...style}}>{children}</div>;
export const Window=({children,x=160,y=175,w=1600,h=710,dark=true,style={}}:any)=><Surface x={x} y={y} w={w} h={h} dark={dark} style={style}><div style={{height:60,background:dark?'#080808':'#eee',display:'flex',gap:13,alignItems:'center',paddingLeft:26}}>{['#ff5f57','#febc2e','#28c840'].map(c=><i key={c} style={{width:13,height:13,borderRadius:20,background:c}}/>)}</div><div style={{position:'absolute',left:0,right:0,top:60,bottom:0,overflow:'hidden'}}>{children}</div></Surface>;
export const Enter=({t,at,children}:any)=><div style={{position:'absolute',inset:0,clipPath:`inset(${100*(1-q(t,at,at+.4))}% 0 0 0)`}}>{children}</div>;
export const Frost=({t,at,children,dark=false}:any)=>{const p=q(t,at,at+.6);return <div style={{position:'absolute',inset:0,background:dark?`rgba(12,12,14,${.72*p})`:`rgba(255,255,255,${.64*p})`,backdropFilter:`blur(${20*p}px)`,color:dark?'#fff':'#111',display:'flex',flexDirection:'column',justifyContent:'center',alignItems:'center',paddingBottom:130}}><div style={{clipPath:`inset(${100*(1-p)}% 0 0)`,transform:`translateY(${35*(1-p)}px)`,textAlign:'center'}}>{children}</div></div>};
export const TextHandoff=({t,at,before,after,size=106}:any)=>{const p=q(t,at,at+.55);return <div style={{position:'relative',height:size*1.4,width:1600,overflow:'hidden',textAlign:'center',fontSize:size,fontWeight:600}}><div style={{position:'absolute',inset:0,transform:`translateY(${-size*1.5*p}px)`}}>{before}</div><div style={{position:'absolute',inset:0,transform:`translateY(${size*1.5*(1-p)}px)`}}>{after}</div></div>};
// Device geometry copied from ep93 Carriers.tsx; content is episode-specific.
export const Phone=({children,style={}}:any)=><div style={{width:430,height:820,borderRadius:76,background:'#111216',padding:18,boxShadow:'0 34px 80px #0003',...style}}><div style={{height:'100%',borderRadius:60,background:'#fff',overflow:'hidden',position:'relative'}}><div style={{position:'absolute',top:14,left:'50%',transform:'translateX(-50%)',width:130,height:34,borderRadius:99,background:'#0b0b0d',zIndex:2}}/>{children}</div></div>;
export const Monitor=({children,style={}}:any)=><div style={{display:'flex',flexDirection:'column',alignItems:'center',...style}}><div style={{width:1340,height:680,border:'24px solid #111216',borderRadius:34,background:'#fff',overflow:'hidden',position:'relative',boxShadow:'0 28px 80px #0000002b'}}>{children}</div><div style={{width:86,height:96,background:'#111216'}}/><div style={{width:330,height:28,borderRadius:99,background:'#111216'}}/></div>;
export const Brand=({x=0,y=0,size=48,label='豆包工作',dark=false}:any)=><div style={{position:'absolute',left:x,top:y,display:'flex',gap:18,alignItems:'center',fontSize:size,fontWeight:600,color:dark?'white':'#111'}}><Img src={staticFile('doubao.png')} style={{width:size*1.3,height:size*1.3,objectFit:'contain'}}/>{label}</div>;
export const Media=({file,x=0,y=0,w=1000,h=500,scale=1,dx=0,dy=0,style={}}:any)=><div style={{position:'absolute',left:x,top:y,width:w,height:h,overflow:'hidden',...style}}><Img src={staticFile(file)} style={{position:'absolute',left:dx,top:dy,width:w,height:'auto',transform:`scale(${scale})`,transformOrigin:'top left'}}/></div>;
