import {AvatarBracketCarousel as C0} from './components/shot-avatar-bracket-carousel';
import {BeatStepListThemeCycle as C1} from './components/shot-beat-step-list-theme-cycle';
import {BrandFrameSnap as C2} from './components/shot-brand-frame-snap';
import {CountdownArcScatter as C5} from './components/shot-countdown-arc-scatter';
import {CursorFlyover as C6} from './components/shot-cursor-flyover';
import {DocParkLeftPillDeal as C7} from './components/shot-doc-park-left-pill-deal';
import {ParticleSandFill as C11} from './components/shot-particle-sand-fill';
import {PickerCarouselFeatureCycle as C12} from './components/shot-picker-carousel-feature-cycle';
import {VerticalWordRollBlurCycle as C16} from './components/shot-vertical-word-roll-blur-cycle';
import C20 from './components/talk-focus-dim-spotlight';
import C21 from './components/talk-highlighter-sweep';
import C22 from './components/talk-scribble-annotation';
import C23 from './components/talk-callout-line-label';
import C24 from './components/talk-converging-arrows';
import C26 from './components/talk-crash-zoom-punch';
import C27 from './components/talk-scanline-annotate';
import C29 from './components/talk-bed-echo-blur';
import C30 from './components/talk-chat-message-flow';
import C31 from './components/talk-cursor-actor-demo';
import C32 from './components/talk-evidence-scroll-tour';
import C33 from './components/talk-still-layout-relay';
import C34 from './components/talk-ui-flow-theater';
import C36 from './components/talk-filmstrip-conveyor';
import C37 from './components/talk-gallery-wall-dolly';
import C38 from './components/talk-glass-code-walk';
import C39 from './components/talk-grid-to-hero';
import C42 from './components/talk-stack-fan-out';
import C43 from './components/talk-terminal-typing-log';
import C44 from './components/talk-word-relay-filmstrip';
import C45 from './components/talk-cursor-locked-zoom';
import C49 from './components/talk-particle-weld-transition';
import C50 from './components/talk-pullback-cool-transition';
import C51 from './components/talk-whip-pan-transition';
import C54 from './components/talk-long-take-world';
import C57 from './components/talk-error-retype';
import {AgentSteps as C62} from './components/snap-agent-steps';
import {TextReveal as C65} from './components/snap-text-reveal';
import {TerminalSimulator as C69} from './components/snap-terminal-simulator';
import {PromptSend as C71} from './components/snap-prompt-send';
import {HeroLaunch as C72} from './components/snap-hero-launch';
export const resolveComponent = (id: string) => { switch (id) {
case 'shot-avatar-bracket-carousel': return C0;
case 'shot-beat-step-list-theme-cycle': return C1;
case 'shot-brand-frame-snap': return C2;
case 'shot-countdown-arc-scatter': return C5;
case 'shot-cursor-flyover': return C6;
case 'shot-doc-park-left-pill-deal': return C7;
case 'shot-particle-sand-fill': return C11;
case 'shot-picker-carousel-feature-cycle': return C12;
case 'shot-vertical-word-roll-blur-cycle': return C16;
case 'talk-focus-dim-spotlight': return C20;
case 'talk-highlighter-sweep': return C21;
case 'talk-scribble-annotation': return C22;
case 'talk-callout-line-label': return C23;
case 'talk-converging-arrows': return C24;
case 'talk-crash-zoom-punch': return C26;
case 'talk-scanline-annotate': return C27;
case 'talk-bed-echo-blur': return C29;
case 'talk-chat-message-flow': return C30;
case 'talk-cursor-actor-demo': return C31;
case 'talk-evidence-scroll-tour': return C32;
case 'talk-still-layout-relay': return C33;
case 'talk-ui-flow-theater': return C34;
case 'talk-filmstrip-conveyor': return C36;
case 'talk-gallery-wall-dolly': return C37;
case 'talk-glass-code-walk': return C38;
case 'talk-grid-to-hero': return C39;
case 'talk-stack-fan-out': return C42;
case 'talk-terminal-typing-log': return C43;
case 'talk-word-relay-filmstrip': return C44;
case 'talk-cursor-locked-zoom': return C45;
case 'talk-particle-weld-transition': return C49;
case 'talk-pullback-cool-transition': return C50;
case 'talk-whip-pan-transition': return C51;
case 'talk-long-take-world': return C54;
case 'talk-error-retype': return C57;
case 'snap-agent-steps': return C62;
case 'snap-text-reveal': return C65;
case 'snap-terminal-simulator': return C69;
case 'snap-prompt-send': return C71;
case 'snap-hero-launch': return C72;
default: throw new Error(`Unknown selected component: ${id}`); }};
