import {InterfaceB035,NavB035,CanvasB035} from './InterfacesB035';
import React,{useState,useEffect} from 'react';import {AbsoluteFill,Img,staticFile,delayRender,continueRender,cancelRender} from 'remotion';
import data from '../../../specs/B035.json';import {measured,type ClipSpec} from '../../../runtime/clip-spec';
export function RebuiltB035({frame,proof=false}:{frame:number;proof?:boolean}){
 const spec=data as unknown as ClipSpec;const phones=data.objects.phones;const canvas=data.objects.canvas;const font=data.fonts[0];const [handle]=useState(()=>delayRender('B035 Fred UI font'));useEffect(()=>{new FontFace(font.family,`url(${staticFile(font.file)})`,{weight:font.weight}).load().then(f=>{document.fonts.add(f);continueRender(handle)}).catch(cancelRender)},[handle,font]);
 return <AbsoluteFill style={{background:'#fff',overflow:'hidden'}}>
 <div style={{position:'absolute',left:canvas.bounds[0],top:canvas.bounds[1],width:canvas.bounds[2],height:canvas.bounds[3],filter:`blur(${measured(spec,'canvasBlur',frame)[0]}px)`}}>{proof?<Img src={staticFile(canvas.proofFile)} style={{width:'100%',height:'100%'}}/>:<CanvasB035 media={data.content.media} text={data.content.text} questions={data.content.reviewUI.questions}/>}</div>
 {data.content.media.map((src,i)=>{const [x,y,w,h]=measured(spec,`phone${i}`,frame);const scroll=measured(spec,`content${i}`,frame)[0];return <div key={i} style={{position:'absolute',left:x,top:y,width:w,height:h,background:phones.fill,borderRadius:phones.radius,boxShadow:phones.shadow,overflow:'hidden'}}>{proof?<Img src={staticFile(phones.proofFiles[i])} style={{width:'100%',height:'100%'}}/>:<div style={{position:'absolute',inset:phones.inset,borderRadius:phones.innerRadius,overflow:'hidden',background:'#f6f3fa'}}><div style={{position:'absolute',top:scroll,left:0,width:'100%',fontFamily:font.family,fontWeight:400,fontSynthesis:'none'}}><InterfaceB035 index={i} media={src} text={data.content.text} questions={data.content.reviewUI.questions}/></div>{i!==0&&<NavB035/>}</div>}</div>})}
 </AbsoluteFill>
}
