import {useCurrentFrame} from 'remotion';
import {CenterCopy,ClipText,LabCanvas,LabSfx,mix,phase,type MotionProps} from './MotionShared';

export const MotionLab01=({spec}:MotionProps)=>{const f=useCurrentFrame();const [a,b,c]=spec.cues;const p=phase(f,a,30);return <LabCanvas dark={false}><div style={{position:'absolute',left:'50%',top:'50%',width:24+p*2300,height:24+p*1420,borderRadius:p<.45?'50%':36,background:'#000',transform:'translate(-50%,-50%)'}}/><ClipText at={b} from="center" style={{position:'absolute',left:0,right:0,top:385,textAlign:'center',fontSize:118,fontWeight:600,color:'#fff'}}>{spec.words[0]}</ClipText><ClipText at={c} from="center" style={{position:'absolute',left:0,right:0,top:550,textAlign:'center',fontSize:150,fontWeight:600,color:'#fff'}}>{spec.words[1]}</ClipText><LabSfx spec={spec}/></LabCanvas>};

export const MotionLab02=({spec}:MotionProps)=>{const f=useCurrentFrame();const [a,b,c]=spec.cues;const p=phase(f,a,28);const w=mix(180,1600,p),h=mix(120,820,p);return <LabCanvas dark={false}><div style={{position:'absolute',left:960-w/2,top:540-h/2,width:w,height:h,borderRadius:mix(60,34,p),background:'#000'}}><ClipText at={b} from="left" style={{position:'absolute',left:120,right:120,top:220,fontSize:104,fontWeight:500,color:'#fff'}}>{spec.words[0]}</ClipText><ClipText at={c} from="right" style={{position:'absolute',left:120,right:120,bottom:190,textAlign:'right',fontSize:150,fontWeight:600,color:'#fff'}}>{spec.words[1]}</ClipText></div><LabSfx spec={spec}/></LabCanvas>};

export const MotionLab03=({spec}:MotionProps)=>{const f=useCurrentFrame();const [a,b,c]=spec.cues;const p=phase(f,a,26),q=phase(f,c,18);return <LabCanvas dark><div style={{position:'absolute',left:0,top:0,width:mix(40,1920,p),height:mix(40,1080,p),borderBottomRightRadius:mix(40,0,p),background:'#fff'}}/><ClipText at={b} style={{position:'absolute',left:150,top:250,fontSize:128,fontWeight:600,color:'#090909'}}>{spec.words[0]}</ClipText><div style={{position:'absolute',left:0,right:0,bottom:0,height:220*q,background:'#000'}}/><ClipText at={c} from="center" style={{position:'absolute',left:0,right:0,bottom:55,textAlign:'center',fontSize:118,fontWeight:600,color:'#fff'}}>{spec.words[1]}</ClipText><LabSfx spec={spec}/></LabCanvas>};

export const MotionLab04=({spec}:MotionProps)=>{const f=useCurrentFrame();const [a,b,c]=spec.cues;const p=phase(f,a,26);return <LabCanvas dark={false}><div style={{position:'absolute',left:0,right:0,top:540-height(p),height:height(p)*2,background:'#000'}}/><ClipText at={b} from="center" style={{position:'absolute',left:0,right:0,top:365,textAlign:'center',fontSize:112,fontWeight:500,color:'#fff'}}>{spec.words[0]}</ClipText><ClipText at={c} from="center" style={{position:'absolute',left:0,right:0,top:545,textAlign:'center',fontSize:142,fontWeight:600,color:'#fff'}}>{spec.words[1]}</ClipText><LabSfx spec={spec}/></LabCanvas>};
function height(p:number){return mix(4,620,p)}

export const MotionLab05=({spec}:MotionProps)=>{const f=useCurrentFrame();const [a,b,c]=spec.cues;const p=phase(f,a,30);return <LabCanvas dark><div style={{position:'absolute',left:340-p*430,top:540-p*710,width:28+p*1450,height:28+p*1450,borderRadius:'50%',background:'#fff'}}/><div style={{position:'absolute',right:340-p*430,top:540-p*710,width:28+p*1450,height:28+p*1450,borderRadius:'50%',background:'#fff'}}/><ClipText at={b} from="left" style={{position:'absolute',left:180,top:360,fontSize:116,fontWeight:500,color:'#090909'}}>{spec.words[0]}</ClipText><ClipText at={c} from="right" style={{position:'absolute',right:180,bottom:320,fontSize:150,fontWeight:600,color:'#090909'}}>{spec.words[1]}</ClipText><LabSfx spec={spec}/></LabCanvas>};

