import {useCurrentFrame} from 'remotion';
import {ClipText,LabCanvas,LabSfx,mix,phase,type MotionProps} from './MotionShared';

export const MotionLab16=({spec}:MotionProps)=>{const f=useCurrentFrame();const [a,b,c]=spec.cues;const p=phase(f,a,24),q=phase(f,c,22);const inset=mix(120,210,q);return <LabCanvas dark={false}><div style={{position:'absolute',left:mix(-760,inset,p),top:170,width:750,height:740,borderRadius:30,background:'#000'}}/><div style={{position:'absolute',right:mix(-760,inset,p),top:170,width:750,height:740,borderRadius:30,background:'#000'}}/><ClipText at={b} from="center" style={{position:'absolute',left:inset+45,width:660,top:430,textAlign:'center',fontSize:86,fontWeight:500,color:'#fff',whiteSpace:'nowrap'}}>{spec.words[0]}</ClipText><ClipText at={c} from="center" style={{position:'absolute',right:inset+45,width:660,top:430,textAlign:'center',fontSize:86,fontWeight:600,color:'#fff',whiteSpace:'nowrap'}}>{spec.words[1]}</ClipText><LabSfx spec={spec}/></LabCanvas>};

export const MotionLab17=({spec}:MotionProps)=>{const f=useCurrentFrame();const [a,b,c]=spec.cues;const p=phase(f,a,20),q=phase(f,c,28);return <LabCanvas dark>{[0,1,2].map((index)=>{const startX=180+index*540;const x=mix(startX,420+index*70,q),y=mix(220+index%2*260,270+index*45,q),w=mix(500,1080-index*140,q),h=mix(260,430-index*70,q);return <div key={index} style={{position:'absolute',left:x,top:y,width:w*p,height:h*p,borderRadius:30,background:'#fff'}}/>})}<ClipText at={b} from="center" style={{position:'absolute',left:0,right:0,top:330,textAlign:'center',fontSize:105,fontWeight:500,color:'#090909'}}>{spec.words[0]}</ClipText><ClipText at={c} from="center" style={{position:'absolute',left:0,right:0,bottom:260,textAlign:'center',fontSize:142,fontWeight:600,color:'#090909'}}>{spec.words[1]}</ClipText><LabSfx spec={spec}/></LabCanvas>};

export const MotionLab18=({spec}:MotionProps)=>{const f=useCurrentFrame();const [a,b,c]=spec.cues;const p=phase(f,a,18),q=phase(f,c,24);return <LabCanvas dark={false}><div style={{position:'absolute',left:0,right:0,top:420-q*180,textAlign:'center',fontSize:mix(160,102,q),fontWeight:600,clipPath:`inset(0 ${(1-p)*50}%)`}}>{spec.words[0]}</div><div style={{position:'absolute',left:230,top:520,width:1460*q,height:300,borderRadius:30,background:'#000'}}/><ClipText at={c} from="center" style={{position:'absolute',left:230,right:230,top:610,textAlign:'center',fontSize:126,fontWeight:600,color:'#fff'}}>{spec.words[1]}</ClipText><LabSfx spec={spec}/></LabCanvas>};

export const MotionLab19=({spec}:MotionProps)=>{const f=useCurrentFrame();const [a,b,c]=spec.cues;const p=phase(f,a,20),q=phase(f,c,28);const starts=[[170,170],[980,170],[170,560],[980,560]];return <LabCanvas dark>{starts.map(([sx,sy],index)=>{const col=index%2,row=Math.floor(index/2);const x=mix(sx,250+col*710,q),y=mix(sy,190+row*350,q);const radius=q>.98?(index===0?'30px 0 0 0':index===1?'0 30px 0 0':index===2?'0 0 0 30px':'0 0 30px 0'):30;return <div key={index} style={{position:'absolute',left:x,top:y,width:mix(770,710,q)*p,height:mix(340,350,q)*p,borderRadius:radius,background:'#fff'}}/>})}<ClipText at={b} from="center" style={{position:'absolute',left:0,right:0,top:320,textAlign:'center',fontSize:100,fontWeight:500,color:'#090909'}}>{spec.words[0]}</ClipText><ClipText at={c} from="center" style={{position:'absolute',left:0,right:0,bottom:285,textAlign:'center',fontSize:136,fontWeight:600,color:'#090909'}}>{spec.words[1]}</ClipText><LabSfx spec={spec}/></LabCanvas>};

export const MotionLab20=({spec}:MotionProps)=>{const f=useCurrentFrame();const [a,b,c]=spec.cues;const p=phase(f,a,28),q=phase(f,c,24);const w=mix(30,1540,p),h=mix(30,760,p);return <LabCanvas dark={false}><div style={{position:'absolute',left:960-w/2,top:540-h/2,width:w,height:h,borderRadius:mix(w/2,34,q),background:'#000'}}><ClipText at={b} from="center" style={{position:'absolute',left:80,right:80,top:190,textAlign:'center',fontSize:100,fontWeight:500,color:'#fff'}}>{spec.words[0]}</ClipText><ClipText at={c} from="center" style={{position:'absolute',left:80,right:80,bottom:165,textAlign:'center',fontSize:148,fontWeight:600,color:'#fff'}}>{spec.words[1]}</ClipText></div><LabSfx spec={spec}/></LabCanvas>};
