import {useCurrentFrame} from 'remotion';
import {CenterCopy,ClipText,LabCanvas,LabSfx,mix,phase,type MotionProps} from './MotionShared';

export const MotionLab06=({spec}:MotionProps)=>{const f=useCurrentFrame();const [a,b,c]=spec.cues;const p=phase(f,a,30);return <LabCanvas dark={false}><div style={{position:'absolute',left:170,top:135,width:1580,height:810,borderRadius:34,background:'#000',transform:`scale(${mix(.12,1,p)})`}}><ClipText at={b} from="center" style={{position:'absolute',left:100,right:100,top:180,textAlign:'center',fontSize:86,fontWeight:500,color:'#fff'}}>{spec.words[0]}</ClipText><ClipText at={c} from="center" style={{position:'absolute',left:100,right:100,bottom:170,textAlign:'center',fontSize:128,fontWeight:600,color:'#fff'}}>{spec.words[1]}</ClipText></div><LabSfx spec={spec}/></LabCanvas>};

export const MotionLab07=({spec}:MotionProps)=>{const f=useCurrentFrame();const [a,b,c]=spec.cues;const p=phase(f,a,20),q=phase(f,c,28);const w=mix(1920,1420,q),h=mix(1080,650,q);return <LabCanvas dark><div style={{position:'absolute',left:960-w/2,top:540-h/2,width:w,height:h,borderRadius:34*q,background:'#fff',clipPath:`inset(0 ${(1-p)*50}%)`}}><ClipText at={b} from="center" style={{position:'absolute',left:80,right:80,top:170,textAlign:'center',fontSize:112,fontWeight:500,color:'#090909'}}>{spec.words[0]}</ClipText><ClipText at={c} from="center" style={{position:'absolute',left:80,right:80,bottom:150,textAlign:'center',fontSize:146,fontWeight:600,color:'#090909'}}>{spec.words[1]}</ClipText></div><LabSfx spec={spec}/></LabCanvas>};

export const MotionLab08=({spec}:MotionProps)=>{const f=useCurrentFrame();const [a,b,c]=spec.cues;const p=phase(f,a,20),q=phase(f,c,26);const h=mix(800,230,q),top=mix(140,720,q);return <LabCanvas dark={false}><div style={{position:'absolute',left:150,right:150,top,height:h,borderRadius:32,background:'#000',clipPath:`inset(0 ${(1-p)*50}%)`}}><ClipText at={b} from="center" style={{position:'absolute',inset:0,display:'flex',alignItems:'center',justifyContent:'center',fontSize:102,fontWeight:500,color:'#fff'}}>{spec.words[0]}</ClipText></div><ClipText at={c} from="center" style={{position:'absolute',left:0,right:0,top:370,textAlign:'center',fontSize:142,fontWeight:600}}>{spec.words[1]}</ClipText><LabSfx spec={spec}/></LabCanvas>};

export const MotionLab09=({spec}:MotionProps)=>{const f=useCurrentFrame();const [a,b,c]=spec.cues;const p=phase(f,a,22),q=phase(f,c,24);return <LabCanvas dark><div style={{position:'absolute',left:180,top:150,width:1560,height:780,borderRadius:34,background:'#fff',clipPath:`inset(0 ${(1-p)*50}%)`}}><ClipText at={b} style={{position:'absolute',left:100,top:115,fontSize:104,fontWeight:500,color:'#090909'}}>{spec.words[0]}</ClipText><div style={{position:'absolute',left:350,top:330,width:860*q,height:310,borderRadius:28,background:'#000',overflow:'hidden'}}><ClipText at={c} from="center" style={{width:860,height:310,display:'flex',alignItems:'center',justifyContent:'center',fontSize:105,fontWeight:600,color:'#fff'}}>{spec.words[1]}</ClipText></div></div><LabSfx spec={spec}/></LabCanvas>};

export const MotionLab10=({spec}:MotionProps)=>{const f=useCurrentFrame();const [a,b,c,d,e]=spec.cues;const p=phase(f,a,22),q=phase(f,d,26);const gap=mix(100,0,q);return <LabCanvas dark={false}><div style={{position:'absolute',left:170,top:180,width:790-gap/2,height:720,borderRadius:30,background:'#000',clipPath:`inset(0 ${(1-p)*100}% 0 0)`}}/><div style={{position:'absolute',right:170,top:180,width:790-gap/2,height:720,borderRadius:30,background:'#000',clipPath:`inset(0 0 0 ${(1-p)*100}%)`}}/>{spec.words.map((word,index)=><ClipText key={word} at={[b,c,d,e][index]??b} from="center" style={{position:'absolute',left:170+index%2*790,top:290+Math.floor(index/2)*260,width:790,textAlign:'center',fontSize:index===3?112:82,fontWeight:index===3?600:500,color:'#fff'}}>{word}</ClipText>)}<LabSfx spec={spec}/></LabCanvas>};
