import {useCurrentFrame} from 'remotion';
import {ClipText,LabCanvas,LabSfx,mix,phase,type MotionProps} from './MotionShared';

export const MotionLab11=({spec}:MotionProps)=>{const f=useCurrentFrame();const [a,b,c]=spec.cues;const p=phase(f,a,22),q=phase(f,c,20);return <LabCanvas dark><div style={{position:'absolute',left:110,top:330,width:1700*p,height:310,background:'#fff'}}/><ClipText at={b} style={{position:'absolute',left:180,top:405,fontSize:112,fontWeight:500,color:'#090909'}}>{spec.words[0]}</ClipText><div style={{position:'absolute',left:180,bottom:210,width:1560*q,height:10,background:'#fff'}}/><ClipText at={c} from="right" style={{position:'absolute',right:180,bottom:250,fontSize:142,fontWeight:600,color:'#fff'}}>{spec.words[1]}</ClipText><LabSfx spec={spec}/></LabCanvas>};

export const MotionLab12=({spec}:MotionProps)=>{const f=useCurrentFrame();const [a,b,c]=spec.cues;const p=phase(f,a,26);return <LabCanvas dark={false}><div style={{position:'absolute',left:150,right:150,top:540-mix(3,390,p),height:mix(6,780,p),borderRadius:32*p,background:'#000'}}><ClipText at={b} from="center" style={{position:'absolute',left:0,right:0,top:210,textAlign:'center',fontSize:112,fontWeight:500,color:'#fff'}}>{spec.words[0]}</ClipText><ClipText at={c} from="center" style={{position:'absolute',left:0,right:0,bottom:185,textAlign:'center',fontSize:152,fontWeight:600,color:'#fff'}}>{spec.words[1]}</ClipText></div><LabSfx spec={spec}/></LabCanvas>};

export const MotionLab13=({spec}:MotionProps)=>{const f=useCurrentFrame();const [a,b,c,d,e]=spec.cues;const p=phase(f,a,24);return <LabCanvas dark>{[0,1,2,3].map((index)=>{const left=index<2?960-(index+1)*420:960+(index-2)*420;const fromCenter=index<2?960-left:0;return <div key={index} style={{position:'absolute',left,top:170,width:400,height:740,background:'#fff',clipPath:index<2?`inset(0 0 0 ${(1-p)*100}%)`:`inset(0 ${(1-p)*100}% 0 0)`}}><ClipText at={[b,c,d,e][index]??b} from="center" style={{position:'absolute',inset:0,display:'flex',alignItems:'center',justifyContent:'center',fontSize:88,fontWeight:index===3?600:500,color:'#090909'}}>{spec.words[index]}</ClipText></div>})}<LabSfx spec={spec}/></LabCanvas>};

export const MotionLab14=({spec}:MotionProps)=>{const f=useCurrentFrame();const [a,b,c]=spec.cues;const ps=[phase(f,a,18),phase(f,a+16,18),phase(f,a+32,18)];return <LabCanvas dark={false}>{ps.map((p,index)=><div key={index} style={{position:'absolute',left:index%2?1920-1720*p:0,top:180+index*265,width:1720*p,height:190,background:'#000'}}/>)}<ClipText at={b} style={{position:'absolute',left:160,right:160,top:222,fontSize:104,fontWeight:500,color:'#fff'}}>{spec.words[0]}</ClipText><ClipText at={c} from="right" style={{position:'absolute',left:160,right:240,top:756,textAlign:'right',fontSize:112,fontWeight:600,color:'#fff'}}>{spec.words[1]}</ClipText><LabSfx spec={spec}/></LabCanvas>};

export const MotionLab15=({spec}:MotionProps)=>{const f=useCurrentFrame();const [a,b,c]=spec.cues;const p=phase(f,a,24);const edge=mix(0,118,p);return <LabCanvas dark><div style={{position:'absolute',inset:0,background:'#fff',clipPath:`polygon(0 0,${edge}% 0,${100-edge/2}% 100%,0 100%)`}}/><ClipText at={b} style={{position:'absolute',left:180,top:300,fontSize:176,fontWeight:600,color:'#090909'}}>{spec.words[0]}</ClipText><ClipText at={c} from="right" style={{position:'absolute',right:150,bottom:185,fontSize:132,fontWeight:600,color:'#fff'}}>{spec.words[1]}</ClipText><LabSfx spec={spec}/></LabCanvas>};
