import {approvedStaticFile as staticFile} from '../../../../material-policy';
import React from 'react';
import {Img} from 'remotion';
export const Document014=({scroll=0}:{scroll?:number})=> <div style={{width:'100%',height:'100%',background:'#fff',color:'#222',fontFamily:'FredRegular',display:'flex',fontSize:15}}><aside style={{width:'32%',padding:'25px 20px',boxSizing:'border-box',borderRight:'1px solid #eee'}}><b>FredTalk · 日常记录使用指南</b>{['开始记录','录音与整理','建立知识库','归档与查找','分享记录'].map((x,i)=><p key={x} style={{color:'#667',marginTop:25}}>▧　步骤 {i+1}　{x}</p>)}</aside><main style={{flex:1,padding:25,overflow:'hidden'}}><div style={{transform:`translateY(${-scroll}px)`}}>{[3,4,5].map((n)=><section key={n}><b>步骤 {n}</b><div style={{height:190,background:'#f3f4f6',margin:'14px 0',padding:14,boxSizing:'border-box',border:'1px solid #ddd'}}><div style={{display:'flex',height:'100%',gap:12}}><div style={{width:105,color:'#999'}}>FredTalk<br/>{['概览','录音','文字记录','知识库','设置'].map(x=><p key={x}>{x}</p>)}</div><div style={{flex:1,color:'#666'}}><h4>整理自己的上下文</h4>{[0,1,2,3].map(i=><div key={i} style={{height:18,marginBottom:11,background:i===2?'#eadfff':'#e3e5e9',width:`${90-i*8}%`}}/>)}</div></div></div></section>)}</div></main></div>;
export const Finder036=()=> <div style={{width:'100%',height:'100%',background:'#fafafa',fontFamily:'FredRegular',fontSize:24,color:'#444'}}><header style={{height:'12%',padding:'25px 40px',boxSizing:'border-box'}}>工作 · 项目资料 / FredTalk 工具箱 <span style={{float:'right'}}>⌕　⊞　☷　•••</span></header><div style={{display:'flex',height:'88%'}}><aside style={{width:'24%',padding:'0 30px',boxSizing:'border-box',background:'#f6f7f8'}}>{['上传文件','日常记录','会议纪要','内容素材','项目资料','个人知识库','归档','最近使用'].map(x=><p key={x} style={{margin:'24px 0'}}>▧　{x}</p>)}</aside><div style={{width:'30%',borderLeft:'1px solid #ddd',borderRight:'1px solid #ddd'}}>{['FredTalk 工作流','记录与整理','会议归档','日常灵感','音频与视频','配置文件'].map((x,i)=><p key={x} style={{padding:'14px 22px',margin:0,background:i===0?'#e5e8ed':'transparent'}}>▣　{x}</p>)}</div><div style={{width:'46%',padding:30,boxSizing:'border-box'}}><div style={{background:'#eee',padding:15}}>fredtalk_workflow.json</div><div style={{textAlign:'center',paddingTop:100}}><div style={{fontSize:150,color:'#99a4b3'}}>⌘</div><p>fredtalk_workflow.json</p><p style={{fontSize:19,color:'#999'}}>JSON 文档 · 12 KB</p></div></div></div></div>;
export const Website033=()=> <div style={{height:'100%',background:'#0c0d0b',fontFamily:'FredRegular',color:'#ddd',overflow:'hidden'}}><header style={{height:60,display:'flex',alignItems:'center',padding:'0 45px',gap:50,fontSize:15}}><b style={{color:'#c99ef4'}}>∞ FredTalk</b><span style={{marginLeft:'auto'}}>首页　　工作流　　视频案例　　资料与社区</span><span style={{background:'#8960ca',borderRadius:20,padding:'4px 15px'}}>CN / EN</span></header><h1 style={{fontSize:66,color:'#b98bea',textAlign:'center',margin:'0 0 18px'}}>FredTalk · 日常记录</h1><h3 style={{textAlign:'center',margin:15}}>留下每天的声音，整理自己的上下文</h3><p style={{maxWidth:1060,margin:'0 auto',lineHeight:1.8,textAlign:'center'}}>记录灵感、会议与交流，使用 AI 整理信息，建立可以持续使用的个人知识库。</p><div style={{display:'flex',justifyContent:'center',gap:25,margin:'25px 0'}}>{['开始记录','工作流','资料库','使用指南','视频案例'].map((x,i)=><div key={x} style={{width:180,padding:'12px 0',textAlign:'center',borderRadius:35,background:i===0?'#8960ca':'#262423',border:'1px solid #555'}}>{x}</div>)}</div><div style={{width:670,margin:'0 auto',padding:20,display:'flex',gap:20,borderRadius:40,background:'#060606'}}>{['fred-walk-portrait.jpg','fred-conversation.jpg','fred-night-review.jpg'].map(x=><Img key={x} src={staticFile('revision/'+x)} style={{width:210,height:400,borderRadius:20,objectFit:'cover'}}/>)}</div></div>;

// R052 closes on an empty asset workspace; preserve the reference's light UI.
export const Workspace052:React.FC<{seconds:number}>=({seconds})=>{
 const q=Math.max(0,Math.min(1,(seconds-9.0)/.7));
 return <div style={{width:'100%',height:'100%',background:'#f8f8f8',fontFamily:'FredRegular',color:'#252525',position:'relative'}}>
  <header style={{height:74,display:'flex',alignItems:'center',padding:'0 42px',gap:30,fontSize:15}}>{['♙ 角色','▧ 场景','◇ 道具','♧ 素材'].map((text,i)=><span key={text} style={{borderBottom:i===0?'2px solid #222':'none',padding:'10px 0'}}>{text}⌄</span>)}<span style={{marginLeft:'auto',background:'#171717',color:'#fff',padding:'9px 22px',borderRadius:30,fontSize:12}}>创建项目</span></header>
  <div style={{position:'absolute',left:45,top:94,width:170,height:206,background:'#f0f0f0',borderRadius:10,display:'flex',alignItems:'center',justifyContent:'center',color:'#bcbcbc',fontSize:32}}>＋</div><span style={{position:'absolute',left:55,top:317,fontSize:13,color:'#666'}}>添加角色素材</span>
  <svg width="28" height="36" viewBox="0 0 28 36" style={{position:'absolute',left:350-265*q,top:120-80*q}}><path d="M3 2L4 28L11 21L16 33L21 30L15 19L25 18Z" fill="white" stroke="#444" strokeWidth="1.5"/></svg>
 </div>;
};
