import {DARK_PURPLE,purpleOnDark,purpleOnSurface} from "../../../surface-purple.ts";
import {FiveFontFace} from "../../../five-fonts.ts";
import React,{useEffect,useState} from 'react';
import {AbsoluteFill,Img,OffthreadVideo,staticFile,delayRender,continueRender,cancelRender} from 'remotion';
import b9 from '../../../specs/B009.json';
import b11 from '../../../specs/B011.json';
import b18 from '../../../specs/B018.json';
import b19 from '../../../specs/B019.json';
import {measured,ClipSpec} from '../../../runtime/clip-spec';
import {cleanStaticFile} from './clean-assets';
type Data=typeof b9;
const clamp=(v:number)=>Math.max(0,Math.min(1,v));
function Media({name,style}:{name:string;style?:React.CSSProperties}){const src=cleanStaticFile(`batch1/${name}.jpg`);return /\.mp4$/.test(src)?<OffthreadVideo muted src={src} style={{width:'100%',height:'100%',objectFit:'cover',...style}}/>:<Img src={src} style={{width:'100%',height:'100%',objectFit:'cover',...style}}/>;}
export function RebuiltBRepresentatives({number,frame}:{number:number;frame:number}){
 const data=({9:b9,11:b11,18:b18,19:b19} as any)[number] as any;
 const spec=data as ClipSpec;const val=(n:string)=>measured(spec,n,frame);
 const [handle]=useState(()=>delayRender(`B${number} measured font`));
 useEffect(()=>{const font=data.fonts[0];new FiveFontFace(font.family,`url(${staticFile(font.file)})`).load().then(f=>{document.fonts.add(f);continueRender(handle)}).catch(cancelRender);},[number,handle]);
 const font=data.fonts[0].family;const words=data.content.texts as string[];const accent=data.content.accent;
 const textStyle:React.CSSProperties={fontFamily:font,fontWeight:400,fontSynthesis:'none',color:number===9?purpleOnDark(accent):accent};
 if(number===9){const o=data.objects;const [blur]=val('blur');const [focus]=val('focus');const [opacity]=val('textOpacity');const [wy]=val('windowY');return <AbsoluteFill style={{background:'white'}}>
 {frame<34&&[0,1,2,3].map(i=><div key={i} style={{position:'absolute',left:(i%2)*994+(i%2?1:-1)*frame*32,top:Math.floor(i/2)*570,width:930,height:500,borderRadius:22,overflow:'hidden'}}><Media name={`prior-nine-${i}`}/></div>)}
 <div style={{position:'absolute',left:o.window.x,top:wy,width:o.window.width,height:o.window.height,background:o.window.fill,borderRadius:o.window.radius,filter:`blur(${blur}px)`,boxShadow:'35px 14px 30px #0004',overflow:'hidden'}}><div style={{height:o.window.headerHeight,background:'#121617',display:'flex',gap:30,paddingLeft:55,alignItems:'center'}}>{['#d92c89','#f6b444','#397df5'].map(c=><div key={c} style={{width:25,height:25,borderRadius:'50%',background:c}}/>)}</div><div style={{position:'absolute',left:o.body.x-o.window.x,top:o.body.y-38,width:o.body.width,...textStyle,fontSize:o.body.fontSize,lineHeight:o.body.lineHeight,opacity}}>{words.map((t,i)=><div key={i}>{t}</div>)}</div></div>
 <div style={{position:'absolute',left:500,top:o.keywords.y,width:920,textAlign:'center',...textStyle,fontSize:o.keywords.fontSize,lineHeight:o.keywords.lineHeight,opacity:focus}}>{o.keywords.texts.map((t:string,i:number)=><div key={i}>{t}</div>)}</div>
 </AbsoluteFill>}
 if(number===11){const [focus]=val('focus');const [fg]=val('foreground');const o=data.objects;return <AbsoluteFill style={{background:'white'}}><AbsoluteFill style={{filter:`blur(${focus*20}px)`}}>{[0,1,2,3].map(i=>{const progress=clamp((frame-o.cards.entryFrames[i])/25);return <div key={i} style={{position:'absolute',left:o.cards.x[i],top:o.cards.y[i],width:o.cards.width,height:o.cards.height,borderRadius:o.cards.radius,overflow:'hidden',transform:`perspective(1500px) rotateY(${(1-progress)*90}deg)`,visibility:frame<o.cards.entryFrames[i]?'hidden':'visible'}}><Media name={`grid-11-${i}-${frame<600?0:frame<720?1:2}`}/><div style={{position:'absolute',inset:0,background:o.focusLuminance[i].overlay,opacity:focus*o.focusLuminance[i].alpha}}/></div>})}</AbsoluteFill><div style={{position:'absolute',left:o.text.x,top:o.text.y,width:o.text.width,...textStyle,fontSize:o.text.fontSize,lineHeight:o.text.lineHeight,textShadow:o.text.shadow,WebkitTextStroke:o.text.stroke,opacity:frame>=360&&frame<=610?fg:0}}>{words.map((t,i)=><div key={i}>{t}</div>)}</div></AbsoluteFill>}
 if(number===18){const [black]=val('ink');const [label]=val('label');const [scale,angle]=val('carrier');return <AbsoluteFill style={{background:'white'}}>{frame<111&&<div style={{position:'absolute',left:580,top:-40,width:760,height:1160,background:'#000',transform:`rotate(${angle}deg) scale(${scale})`}}/>}{[0,1,2,3].map(i=>{const [x,y,w,h]=val('pill'+i);const shade=Math.round(255*(1-val('ink'+i)[0]));return <div key={i} style={{position:'absolute',left:x,top:y,width:w,height:h,background:`rgb(${shade},${shade},${shade})`,borderRadius:58,boxShadow:black>.5?'30px 14px 20px #0004':undefined,display:'flex',alignItems:'center',justifyContent:'center',...textStyle,color:purpleOnSurface(accent,shade),fontSize:142,overflow:'hidden'}}>{i===0&&<span style={{opacity:label}}>{words[0]}</span>}</div>})}{frame>=177&&frame<330&&<div style={{position:'absolute',left:frame<210?1920-(frame-177)*35:770,top:240+(frame>309?(frame-309)*42:0),width:1098,height:600,borderRadius:48,overflow:'hidden'}}><Media name="workflow-eighteen"/></div>}{frame>=316&&frame<462&&<div style={{position:'absolute',left:960,top:406,width:920,...textStyle,fontSize:220,opacity:clamp((frame-316)/16)*(1-clamp((frame-444)/18))}}>{words[1]}</div>}{[0,1].map(i=>frame>(i?552:488)&&<div key={i} style={{position:'absolute',left:i?1320:120,top:430,width:480,height:390,transform:`scale(${clamp((frame-(i?552:488))/24)})`}}><Media name={i?'gpu-right':'gpu-left'} style={{objectFit:'contain'}}/></div>)}</AbsoluteFill>}
 const [x,y,w,h]=val('card');const [op,ty,ts]=val('title');const o=data.objects;return <AbsoluteFill style={{background:'white'}}>{[0,1,2].map(i=>{const [cardX,cardY,cardW,cardH]=val('card'+i);const replace=clamp((frame-o.replaceFrames[i])/24);return <div key={i} style={{position:'absolute',left:cardX,top:cardY,width:cardW,height:cardH,borderRadius:o.card.radius*cardW/468,background:'#969696',overflow:'hidden',boxShadow:'30px 16px 22px #0004'}}><div style={{width:'100%',height:'100%',opacity:clamp((frame-[22,-8,60][i])/24)}}><Media name={`category-${i}`}/></div><div style={{position:'absolute',inset:0,background:'black',opacity:replace}}/><div style={{position:'absolute',top:'50%',left:0,width:'100%',transform:'translateY(-50%)',...textStyle,color:'white',fontSize:o.card.textSize*cardW/468,textAlign:'center',lineHeight:1.08,opacity:clamp((frame-[22,-8,60][i])/24)}}><span style={{opacity:1-replace}}>{words[i]}</span><span style={{position:'absolute',left:0,top:'50%',transform:'translateY(-50%)',width:'100%',fontSize:o.card.replacementTextSize*cardW/468,opacity:replace}}>{words[6+i].slice(0,2)}<br/>{words[6+i].slice(2)}</span></div></div>})}<div style={{position:'absolute',left:50,top:ty,width:1820,...textStyle,fontSize:o.title.fontSize,opacity:op,textAlign:'center',whiteSpace:'nowrap',transform:`scale(${ts})`,transformOrigin:'center top'}}>{frame<273?words[3]:`${words[3]} ${words[5]} ${words[4]}`}</div>{frame>=750&&<><div style={{position:'absolute',left:400,top:18,width:1120,textAlign:'center',...textStyle,fontSize:110,opacity:clamp((frame-750)/10),textShadow:'4px 4px 7px #0008'}}>{words[6]}</div>{[0,1].map(i=><div key={i} style={{position:'absolute',left:i?1390:280,top:998,width:260,textAlign:'center',...textStyle,fontSize:64,transform:`scale(${.4+.6*clamp((frame-753)/25)})`,transformOrigin:'center bottom',textShadow:'3px 3px 5px #0007'}}>{words[i?4:3]}</div>)}{frame>=776&&[0,1].map(i=><div key={i} style={{position:'absolute',left:i?1920-clamp((frame-776)/3)*8:-520+clamp((frame-776)/3)*8,top:170,width:520,height:740,borderRadius:40,overflow:'hidden'}}><Media name={`category-${i?2:0}`}/></div>)}</>}</AbsoluteFill>
}
