import {useCurrentFrame} from 'remotion';
import type {CSSProperties,ReactNode} from 'react';
import type {V8Spec} from './types';
import {activeIndex,BigCopy,Clip,FixedPanel,Sfx,V8Canvas} from './V8Shared';

const Desktop=({children,style}:{children?:ReactNode;style?:CSSProperties})=><div style={{position:'absolute',width:900,height:590,borderRadius:34,background:'#0b0b0b',padding:24,boxShadow:'0 32px 70px rgba(0,0,0,.2)',...style}}><div style={{position:'relative',width:'100%',height:'100%',borderRadius:20,background:'#f0f0ed',overflow:'hidden'}}>{children}</div><div style={{position:'absolute',left:'44%',bottom:-80,width:'12%',height:82,background:'#171717',borderRadius:'0 0 18px 18px'}}/></div>;
const Phone=({children,style}:{children?:ReactNode;style?:CSSProperties})=><div style={{position:'absolute',width:360,height:700,borderRadius:62,background:'#0a0a0a',padding:20,boxShadow:'0 30px 65px rgba(0,0,0,.24)',...style}}><div style={{position:'relative',width:'100%',height:'100%',borderRadius:45,background:'#f1f1ee',overflow:'hidden'}}>{children}</div></div>;
const Blocks=({dark=false}:{dark?:boolean})=><div style={{position:'absolute',inset:55,display:'flex',flexDirection:'column',gap:26}}>{[.55,1,.78,.9].map((width,index)=><div key={index} style={{width:`${width*100}%`,height:index===0?70:48,borderRadius:18,background:index===0?(dark?'#fff':'#090909'):(dark?'#333':'#cfcfcb')}}/>)}</div>;

export const V8DevicesMedia=({spec}:{spec:V8Spec})=>{
  const frame=useCurrentFrame();const [a,b,c,d,e]=spec.cues;
  if(spec.layout==='desktop-system-focus') return <V8Canvas dark={false}><Clip at={a} from="center"><Desktop style={{left:170,top:170}}><Blocks/><BigCopy style={{position:'absolute',left:420,right:70,bottom:70,fontSize:78}}>{spec.words[0]}</BigCopy></Desktop></Clip><Clip at={b} from="right"><FixedPanel dark style={{right:130,top:300,width:720,height:420,display:'flex',alignItems:'center',justifyContent:'center'}}><BigCopy dark style={{fontSize:104}}>{spec.words[1]}</BigCopy></FixedPanel></Clip><Sfx spec={spec}/></V8Canvas>;
  if(spec.layout==='device-network-stage') return <V8Canvas dark><Clip at={a} from="center"><Desktop style={{left:120,top:170,width:1040,height:650}}><div style={{position:'absolute',inset:0,background:'#111'}}><Blocks dark/></div></Desktop><Phone style={{right:170,top:210,width:330,height:640}}><div style={{position:'absolute',inset:0,background:'#fff'}}><Blocks/></div></Phone></Clip><Clip at={b} from="right" style={{right:100,bottom:70,width:1030,height:170,background:'#fff',color:'#090909',borderRadius:26,display:'flex',alignItems:'center',justifyContent:'center',fontSize:84,fontWeight:600}}>{spec.words[1]}</Clip><BigCopy dark style={{position:'absolute',left:150,top:70,fontSize:92}}>{spec.words[0]}</BigCopy><Sfx spec={spec}/></V8Canvas>;
  if(spec.layout==='dual-device-cost-choice') return <V8Canvas dark={false}><Clip at={a} from="center"><Desktop style={{left:110,top:190,width:1040,height:620}}><Blocks/><BigCopy style={{position:'absolute',left:90,right:90,bottom:65,fontSize:70}}>{spec.words[0]}</BigCopy></Desktop><Phone style={{right:150,top:180,width:360,height:700}}><div style={{position:'absolute',inset:0,background:'#090909'}}/><BigCopy dark style={{position:'absolute',left:30,right:30,top:250,fontSize:68}}>{spec.words[1]}</BigCopy></Phone></Clip><Sfx spec={spec}/></V8Canvas>;
  if(spec.layout==='evidence-search-stage') return <V8Canvas dark={false}><Clip at={a} from="center"><FixedPanel style={{left:140,top:130,width:1640,height:820}}><div style={{position:'absolute',left:90,right:90,top:75,height:120,borderRadius:60,background:'#090909'}}>{}</div><BigCopy style={{position:'absolute',left:80,right:80,top:235,fontSize:82}}>{spec.words[0]}</BigCopy>{[0,1,2].map((index)=><div key={index} style={{position:'absolute',left:100,top:400+index*115,width:900+index*180,height:82,borderRadius:18,background:index===2?'#090909':'#d3d3cf'}}/>)}<Clip at={b} from="right" style={{right:70,bottom:55,width:850,height:145,background:'#090909',color:'#fff',borderRadius:22,display:'flex',alignItems:'center',justifyContent:'center',fontSize:72,fontWeight:600}}>{spec.words[1]}</Clip></FixedPanel></Clip><Sfx spec={spec}/></V8Canvas>;
  if(spec.layout==='linear-project-workspace') return <V8Canvas dark><Clip at={a} from="center"><FixedPanel dark style={{left:120,top:110,width:1680,height:860,background:'#0e0e0e'}}><div style={{position:'absolute',left:70,top:70,bottom:70,width:330,borderRadius:24,background:'#181818'}}/><div style={{position:'absolute',left:440,right:70,top:70,height:210,borderRadius:24,background:'#1e1e1e'}}/><div style={{position:'absolute',left:440,right:360,top:320,bottom:70,borderRadius:24,background:'#151515'}}/><div style={{position:'absolute',right:70,top:320,bottom:70,width:250,borderRadius:24,background:'#242424'}}/><BigCopy dark style={{position:'absolute',left:460,right:100,bottom:150,fontSize:98}}>{spec.words[0]}</BigCopy></FixedPanel></Clip><Sfx spec={spec}/></V8Canvas>;
  if(spec.layout==='error-checklist-stage') return <V8Canvas dark={false}><Clip at={a} from="center"><FixedPanel style={{left:180,top:140,width:1560,height:800}}>{['输入','步骤','结果'].map((label,index)=><div key={label} style={{position:'absolute',left:100,top:90+index*190,width:1360,height:150,borderRadius:24,background:index===1?'#090909':'#dededb',color:index===1?'#fff':'#090909',display:'flex',alignItems:'center',paddingLeft:55,fontSize:62,fontWeight:600}}>{label}</div>)}<BigCopy style={{position:'absolute',right:90,bottom:55,fontSize:92}}>{spec.words[0]}</BigCopy></FixedPanel></Clip><Sfx spec={spec}/></V8Canvas>;
  if(spec.layout==='human-device-handoff') return <V8Canvas dark={false}><Clip at={a} from="center"><Phone style={{left:190,top:180,width:340,height:680}}><Blocks/></Phone><Desktop style={{right:130,top:210,width:1050,height:620}}><Blocks/><div style={{position:'absolute',right:55,bottom:55,width:420,height:170,borderRadius:24,background:'#090909'}}/></Desktop></Clip><BigCopy style={{position:'absolute',left:560,right:150,bottom:80,fontSize:104}}>{spec.words[0]}</BigCopy><Sfx spec={spec}/></V8Canvas>;
  if(spec.layout==='raycast-selection-grid') return <V8Canvas dark><div style={{position:'absolute',left:160,right:160,top:190,bottom:190,display:'grid',gridTemplateColumns:'repeat(3,1fr)',gridTemplateRows:'1fr 1fr',gap:22}}>{[0,1,2,3,4,5].map((index)=><div key={index} style={{borderRadius:28,background:index===4?'#fff':'#151515',color:index===4?'#090909':'#555',display:'flex',alignItems:'center',justifyContent:'center',fontSize:index===4?74:42,fontWeight:600,textAlign:'center',padding:35}}>{index===4?spec.words[0]:''}</div>)}</div><Sfx spec={spec}/></V8Canvas>;
  if(spec.layout==='workflow-media-board') {const active=activeIndex(frame,spec.cues,4);return <V8Canvas dark={false}><div style={{position:'absolute',left:130,right:130,top:150,bottom:150,display:'grid',gridTemplateColumns:'1fr 1fr',gridTemplateRows:'1fr 1fr',gap:20}}>{spec.words.map((word,index)=><div key={word} style={{borderRadius:28,background:index===active?'#090909':'#ececea',color:index===active?'#fff':'#777',display:'flex',alignItems:'center',justifyContent:'center',fontSize:94,fontWeight:600}}>{word}</div>)}</div><Sfx spec={spec}/></V8Canvas>}
  if(spec.layout==='answer-ability-doc-flow') return <V8Canvas dark={false}><Clip at={a} from="left"><FixedPanel style={{left:130,top:170,width:750,height:740}}><Blocks/><BigCopy style={{position:'absolute',left:60,right:60,bottom:80,fontSize:88}}>{spec.words[0]}</BigCopy></FixedPanel></Clip><Clip at={b} from="right"><FixedPanel dark style={{right:130,top:170,width:750,height:740}}><div style={{position:'absolute',left:80,right:80,top:90,height:420,borderRadius:28,background:'#fff'}}/><BigCopy dark style={{position:'absolute',left:60,right:60,bottom:80,fontSize:88}}>{spec.words[1]}</BigCopy></FixedPanel></Clip><Sfx spec={spec}/></V8Canvas>;
  if(spec.layout==='five-book-shelf-stage') return <V8Canvas dark><BigCopy dark style={{position:'absolute',left:0,right:0,top:70,fontSize:90}}>{spec.words[0]}</BigCopy><div style={{position:'absolute',left:210,right:210,top:260,height:520,display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:24}}>{['#fff','#2a2a2a','#d9d9d5','#161616','#f0f0ed'].map((color,index)=><Clip key={index} at={a+index*18} from="top" style={{left:index*290,top:0,width:260,height:520,borderRadius:18,background:color}}><div style={{position:'absolute',left:28,right:28,top:40,height:18,background:index%2?'#777':'#090909'}}/></Clip>)}</div><Clip at={b} from="center" style={{left:440,right:440,bottom:70,height:150,background:'#fff',color:'#090909',borderRadius:24,display:'flex',alignItems:'center',justifyContent:'center',fontSize:82,fontWeight:600}}>{spec.words[1]}</Clip><Sfx spec={spec}/></V8Canvas>;
  return <V8Canvas dark><FixedPanel dark style={{left:140,top:140,width:1640,height:800,background:'#101010'}}><div style={{position:'absolute',left:70,right:70,top:70,height:230,borderRadius:24,background:'#1c1c1c',display:'flex',alignItems:'center',justifyContent:'center'}}><BigCopy dark style={{fontSize:88,color:'#777'}}>{spec.words[0]}</BigCopy></div><Clip at={b} from="center" style={{left:70,right:70,bottom:70,height:390,borderRadius:26,background:'#fff',color:'#090909',display:'flex',alignItems:'center',justifyContent:'center',fontSize:120,fontWeight:600}}>{spec.words[1]}</Clip></FixedPanel><Sfx spec={spec}/></V8Canvas>;
};

