import {useCurrentFrame} from 'remotion';
import type {V8Spec} from './types';
import {activeIndex,BigCopy,Clip,FixedPanel,FullCenter,Sfx,V8Canvas} from './V8Shared';

export const V8Product=({spec}:{spec:V8Spec})=>{
  const frame=useCurrentFrame();const [a,b,c,d]=spec.cues;
  if(spec.layout==='claude-checklist-proof') return <V8Canvas dark={false}><Clip at={a} from="center"><FixedPanel style={{left:150,top:130,width:1620,height:760}}><BigCopy style={{position:'absolute',left:80,right:80,top:80,fontSize:86}}>{spec.words[0]}</BigCopy>{['确认输入','检查步骤','核对结果'].map((text,index)=><div key={text} style={{position:'absolute',left:100,top:260+index*130,width:620+index*180,height:92,borderRadius:20,background:index===2?'#090909':'#d8d8d4',color:index===2?'#fff':'#090909',display:'flex',alignItems:'center',paddingLeft:38,fontSize:48,fontWeight:600}}>{text}</div>)}</FixedPanel></Clip><Clip at={b} from="right" style={{right:150,bottom:70,width:1180,height:170,background:'#090909',color:'#fff',borderRadius:26,display:'flex',alignItems:'center',justifyContent:'center',fontSize:76,fontWeight:600}}>{spec.words[1]}</Clip><Sfx spec={spec}/></V8Canvas>;
  if(spec.layout==='linear-output-ability'||spec.layout==='linear-final-choice'){
    const second=frame>=b;return <V8Canvas dark><FixedPanel dark style={{left:140,top:120,width:1640,height:840,background:'#101010'}}><div style={{position:'absolute',left:80,right:80,top:80,height:220,background:second?'#1d1d1d':'#fff',color:second?'#777':'#090909',borderRadius:24,display:'flex',alignItems:'center',justifyContent:'center',fontSize:116,fontWeight:600}}>{spec.words[0]}</div><div style={{position:'absolute',left:80,right:80,bottom:80,height:360,background:second?'#fff':'#171717',color:second?'#090909':'#777',borderRadius:24,display:'flex',alignItems:'center',justifyContent:'center',fontSize:second?118:96,fontWeight:600,textAlign:'center',padding:70}}>{spec.words[1]}</div></FixedPanel><Sfx spec={spec}/></V8Canvas>;
  }
  if(spec.layout==='codex-judgment-first') return <V8Canvas dark={false}><Clip at={a} from="center"><FixedPanel style={{left:170,top:130,width:1580,height:820}}><BigCopy style={{position:'absolute',left:80,right:80,top:70,fontSize:94}}>{spec.words[0]}</BigCopy><div style={{position:'absolute',left:100,top:270,width:1380,height:180,borderRadius:24,background:'#090909'}}/><div style={{position:'absolute',left:100,top:500,width:900,height:110,borderRadius:20,background:'#d2d2ce'}}/><div style={{position:'absolute',left:100,top:650,width:1180,height:90,borderRadius:20,background:'#e0e0dc'}}/></FixedPanel></Clip><Clip at={b} from="right" style={{right:120,bottom:80,width:880,height:160,background:'#090909',color:'#fff',borderRadius:24,display:'flex',alignItems:'center',justifyContent:'center',fontSize:84,fontWeight:600}}>{spec.words[1]}</Clip><Sfx spec={spec}/></V8Canvas>;
  if(spec.layout==='raycast-evidence-slots'){
    const active=activeIndex(frame,spec.cues,3);return <V8Canvas dark><div style={{position:'absolute',left:150,right:150,top:210,bottom:210,display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:22}}>{spec.words.map((word,index)=><div key={word} style={{borderRadius:28,background:index===active?'#fff':'#151515',color:index===active?'#090909':'#777',display:'flex',alignItems:'center',justifyContent:'center',fontSize:112,fontWeight:600}}>{word}</div>)}</div><Sfx spec={spec}/></V8Canvas>;
  }
  if(spec.layout==='linear-system-stage') return <V8Canvas dark><Clip at={a} from="center"><FixedPanel dark style={{left:130,top:120,width:1660,height:840,background:'#0e0e0e'}}><BigCopy dark style={{position:'absolute',left:90,top:100,width:720,textAlign:'left',fontSize:118}}>{spec.words[0]}</BigCopy><div style={{position:'absolute',right:80,top:80,width:650,height:200,borderRadius:22,background:'#1d1d1d'}}/><div style={{position:'absolute',right:80,top:320,width:820,height:180,borderRadius:22,background:'#171717'}}/><div style={{position:'absolute',right:80,top:540,width:560,height:180,borderRadius:22,background:'#242424'}}/></FixedPanel></Clip><Sfx spec={spec}/></V8Canvas>;
  if(spec.layout==='codex-error-stage') return <V8Canvas dark={false}><div style={{position:'absolute',left:180,right:180,top:180,bottom:180,display:'grid',gridTemplateRows:'repeat(3,1fr)',gap:22}}><div style={{borderRadius:24,background:'#ededeb'}}/><Clip at={a} from="left" style={{left:0,top:220,width:1560,height:220,borderRadius:24,background:'#090909',color:'#fff',display:'flex',alignItems:'center',justifyContent:'center',fontSize:118,fontWeight:600}}>{spec.words[0]}</Clip><div style={{borderRadius:24,background:'#ededeb'}}/></div><Sfx spec={spec}/></V8Canvas>;
  if(spec.layout==='claude-ability-stage') return <V8Canvas dark={false}><Clip at={a} from="center"><FixedPanel style={{left:210,top:140,width:1500,height:800}}><div style={{position:'absolute',left:90,right:90,top:90,height:120,borderRadius:22,background:'#d7d7d3'}}/><div style={{position:'absolute',left:90,width:940,top:265,height:100,borderRadius:20,background:'#e2e2df'}}/><BigCopy style={{position:'absolute',left:90,right:90,bottom:130,fontSize:136}}>{spec.words[0]}</BigCopy></FixedPanel></Clip><Sfx spec={spec}/></V8Canvas>;
  if(spec.layout==='raycast-choice-lock') return <V8Canvas dark><div style={{position:'absolute',left:140,right:140,top:220,bottom:220,display:'grid',gridTemplateColumns:'1fr 1.35fr 1fr',gap:24}}><div style={{borderRadius:28,background:'#151515'}}/><Clip at={a} from="center" style={{left:510,top:0,width:650,height:640,borderRadius:28,background:'#fff',color:'#090909',display:'flex',alignItems:'center',justifyContent:'center',fontSize:104,fontWeight:600,textAlign:'center',padding:50}}>{spec.words[0]}</Clip><div style={{borderRadius:28,background:'#151515'}}/></div><Sfx spec={spec}/></V8Canvas>;
  return <V8Canvas dark={false}><Clip at={a} from="center"><FullCenter size={154}>{spec.words[0]}</FullCenter></Clip>{spec.words[1]?<Clip at={b} from="right"><FixedPanel dark style={{left:230,top:500,width:1460,height:330,display:'flex',alignItems:'center',justifyContent:'center'}}><BigCopy dark style={{fontSize:118}}>{spec.words[1]}</BigCopy></FixedPanel></Clip>:null}<Sfx spec={spec}/></V8Canvas>;
};
