import {useCurrentFrame} from 'remotion';
import type {V8Spec} from './types';
import {activeIndex,BigCopy,Clip,FixedPanel,FullCenter,Sfx,V8Canvas} from './V8Shared';

export const V8Redesign=({spec}:{spec:V8Spec})=>{
  const frame=useCurrentFrame();const [a,b,c,d,e]=spec.cues;
  if(spec.layout==='notion-path-reveal'){
    const active=activeIndex(frame,spec.cues,4);const final=frame>=e;
    return <V8Canvas dark={false}>{final?<div style={{position:'absolute',left:130,right:130,top:320,height:440,display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:18}}>{spec.words.map((word,index)=><div key={word} style={{display:'flex',alignItems:'center',justifyContent:'center',borderRadius:26,background:index===3?'#090909':'#f0f0ee',color:index===3?'#fff':'#090909',fontSize:86,fontWeight:600}}>{word}</div>)}</div>:<FullCenter size={190}>{spec.words[active]}</FullCenter>}<Sfx spec={spec}/></V8Canvas>;
  }
  if(spec.layout==='evidence-document-stage') return <V8Canvas dark={false}><Clip at={a} from="center"><FixedPanel style={{left:170,top:120,width:1580,height:720,background:'#f3f3f1'}}><BigCopy style={{position:'absolute',left:80,top:70,textAlign:'left',fontSize:88}}>{spec.words[0]}</BigCopy><div style={{position:'absolute',left:80,right:80,top:230,height:150,borderRadius:22,background:'#090909'}}/><div style={{position:'absolute',left:80,width:850,top:420,height:92,borderRadius:18,background:'#c9c9c5'}}/><div style={{position:'absolute',left:80,width:1060,top:548,height:92,borderRadius:18,background:'#d9d9d5'}}/></FixedPanel></Clip><Clip at={b} from="right" style={{right:130,bottom:86,width:970,height:180,background:'#090909',color:'#fff',borderRadius:26,display:'flex',alignItems:'center',justifyContent:'center',fontSize:92,fontWeight:600}}>{spec.words[1]}</Clip><Sfx spec={spec}/></V8Canvas>;
  if(spec.layout==='mosaic-to-conclusion') {const final=frame>=b;return <V8Canvas dark={false}>{final?<Clip at={b} from="center"><FullCenter size={156}>{spec.words[1]}</FullCenter></Clip>:<><BigCopy style={{position:'absolute',left:0,right:0,top:84}}>{spec.words[0]}</BigCopy><div style={{position:'absolute',left:150,right:150,top:270,bottom:120,display:'grid',gridTemplateColumns:'repeat(3,1fr)',gridTemplateRows:'1fr 1fr',gap:18}}>{['#090909','#dededb','#c9c9c6','#efefed','#151515','#d6d6d2'].map((color,index)=><div key={index} style={{borderRadius:24,background:color}}/>)}</div></>}<Sfx spec={spec}/></V8Canvas>}
  if(spec.layout==='claude-prompt-result') return <V8Canvas dark={false}><Clip at={a} from="center"><FixedPanel style={{left:210,top:150,width:1500,height:300,display:'flex',alignItems:'center',padding:'0 80px'}}><BigCopy style={{fontSize:94,textAlign:'left'}}>{spec.words[0]}</BigCopy></FixedPanel></Clip><Clip at={b} from="center"><FixedPanel dark style={{left:210,top:520,width:1500,height:380,display:'flex',alignItems:'center',justifyContent:'center'}}><BigCopy dark style={{fontSize:122}}>{spec.words[1]}</BigCopy></FixedPanel></Clip><Sfx spec={spec}/></V8Canvas>;
  if(spec.layout==='apple-slot-replace'){const second=frame>=b;return <V8Canvas dark={false}><FullCenter size={second?178:160}>{second?spec.words[1]:spec.words[0]}</FullCenter><div style={{position:'absolute',left:580,right:580,bottom:190,height:18,borderRadius:10,background:'#090909'}}/><Sfx spec={spec}/></V8Canvas>}
  if(spec.layout==='product-cost-choice-panels') return <V8Canvas dark={false}><Clip at={a} from="center"><FixedPanel dark style={{left:130,top:150,width:790,height:760,display:'flex',alignItems:'center',justifyContent:'center'}}><div style={{position:'absolute',left:70,right:70,top:70,height:320,borderRadius:22,background:'#202020'}}/><BigCopy dark style={{position:'absolute',left:60,right:60,bottom:105,fontSize:86}}>{spec.words[0]}</BigCopy></FixedPanel></Clip><Clip at={b} from="right"><FixedPanel style={{right:130,top:150,width:790,height:760,display:'flex',alignItems:'center',justifyContent:'center'}}><div style={{position:'absolute',left:70,right:70,top:70,height:320,borderRadius:22,background:'#090909'}}/><BigCopy style={{position:'absolute',left:60,right:60,bottom:105,fontSize:86}}>{spec.words[1]}</BigCopy></FixedPanel></Clip><Sfx spec={spec}/></V8Canvas>;
  return <V8Canvas dark={false}><div style={{position:'absolute',left:160,right:160,top:210,bottom:180,display:'grid',gridTemplateColumns:'1fr 1fr',gap:28}}>{spec.words.map((word,index)=><FixedPanel key={word} dark={index===1} style={{position:'relative',display:'flex',alignItems:'center',justifyContent:'center',background:index===1?'#090909':'#efefed'}}><BigCopy dark={index===1} style={{fontSize:104}}>{word}</BigCopy></FixedPanel>)}</div><div style={{position:'absolute',left:frame>=b?960:160,top:170,width:800,height:14,background:'#090909'}}/><Sfx spec={spec}/></V8Canvas>;
};
