import {DARK_PURPLE,purpleOnDark,purpleOnSurface} from "../../../surface-purple.ts";
import {FiveFontFace} from "../../../five-fonts.ts";
import {B024Screen} from './B024Screen';
import React,{useEffect,useState} from 'react';
import {AbsoluteFill,Img,OffthreadVideo,staticFile,delayRender,continueRender,cancelRender} from 'remotion';
import d7 from '../../../specs/B007.json';import d16 from '../../../specs/B016.json';import d24 from '../../../specs/B024.json';import {measured,ClipSpec} from '../../../runtime/clip-spec';import {cleanStaticFile} from './clean-assets';
const clamp=(x:number)=>Math.max(0,Math.min(1,x));
export function RebuiltBGeometric({number,frame}:{number:number;frame:number}){const data:any=({7:d7,16:d16,24:d24} as any)[number];const val=(s:string)=>measured(data as ClipSpec,s,frame);const [handle]=useState(()=>delayRender('measured geometry font'));useEffect(()=>{if(!data.fonts.length){continueRender(handle);return}const f=data.fonts[0];new FiveFontFace(f.family,`url(${staticFile(f.file)})`).load().then(f=>{document.fonts.add(f);continueRender(handle)}).catch(cancelRender)},[handle,number]);
 if(number===16){const [x,y,w,h]=val('window');const o=data.objects;return <AbsoluteFill style={{background:'white'}}>{frame>=262&&<AbsoluteFill style={{opacity:val('nextSceneOpacity')[0]}}><OffthreadVideo muted src={staticFile(data.objects.nextScene.media)} style={{width:'100%',height:'100%',objectFit:'cover'}}/></AbsoluteFill>}<div style={{position:'absolute',left:x,top:y,width:w,height:h,background:o.window.fill,borderRadius:o.window.radius,overflow:'hidden',boxShadow:'35px 17px 28px #0004'}}><div style={{height:o.window.header,background:'#131718',display:'flex',alignItems:'center',gap:25,paddingLeft:45}}>{['#d92c89','#f6b444','#397df5'].map(c=><div key={c} style={{width:22,height:22,borderRadius:'50%',background:c}}/>)}</div>{data.content.texts.map((t:string,i:number)=>{const textStyle:React.CSSProperties={position:'absolute',left:0,top:o.text.baselineTop[i]-80,width:'100%',textAlign:'center',fontFamily:data.fonts[0].family,fontSize:o.text.fontSize,lineHeight:o.text.lineHeight,color:'white'};const [roll,alpha]=val(i?'secondRoll':'firstRoll');const mask=i?o.text.rollMask:o.text.firstRollMask;const blur=i?(frame<105?Math.max(0,(105-frame)*.35):0):(frame<10?Math.max(0,(10-frame)*.18):0);return <div key={i} style={{position:'absolute',left:0,top:mask[0],width:'100%',height:mask[1],overflow:'hidden',opacity:alpha,maskImage:'linear-gradient(transparent,black 15%,black 85%,transparent)'}}>{[-1,0,1].map(copy=><div key={copy} style={{...textStyle,top:o.text.baselineTop[i]-80-mask[0]+roll+copy*o.text.rollPeriod,filter:blur?`blur(${blur}px)`:undefined}}>{t}</div>)}</div>})}</div></AbsoluteFill>}
 const o=data.objects.phone;return <AbsoluteFill style={{background:'white'}}>{number===7&&frame<=60&&(()=>{const [x,y,w,h,opacity]=val('departingPrompt');return <div style={{position:'absolute',left:x,top:y,width:1000,height:h,opacity,background:'#202124',borderRadius:24,overflow:'hidden',boxShadow:'20px 10px 22px #0004'}}><div style={{height:65,background:'#131718',display:'flex',gap:20,paddingLeft:40,alignItems:'center'}}>{['#d92c89','#f6b444','#397df5'].map(c=><div key={c} style={{width:18,height:18,borderRadius:'50%',background:c}}/>)}</div><div style={{fontFamily:data.fonts[0].family,fontSize:122,color:purpleOnDark(data.content.accent),padding:'100px 50px 20px',lineHeight:1}}>{data.objects.departingPrompt.text}</div></div>})()}{[0,1,2].map(i=>{const [x,y,w,h]=val('device'+i);if(w<1||h<1)return null;const sx=w/440,sy=h/950;return <div key={i} style={{position:'absolute',left:x,top:y,width:w,height:h,zIndex:number===24?(i===1?2:1):undefined,background:'black',borderRadius:o.radius*sx,boxShadow:'24px 15px 24px #0004',padding:8*sx,boxSizing:'border-box'}}><div style={{position:'relative',width:'100%',height:'100%',borderRadius:46*sx,overflow:'hidden',background:number===7?(frame<65?'white':['#eee4fa','#f4e6f5','#ede8fa'][i]):'white'}}>{number===24?<B024Screen index={i} scale={(w-16*sx)/462}/> :<>{((frame<310?'first':frame<745?(i===0?'first':'second'):(i===0?'first':i===1?'third':'second'))==='first'?[{x:28,y:18,w:44,h:20,r:100,c:'#d1b8f2',a:148},{x:8,y:49,w:84,h:7,r:18,c:'#a888d3',a:225}]:((frame<745?'second':i===1?'third':'second')==='third'?[{x:10,y:15,w:80,h:28,r:30,c:'#faf7fd',a:850},{x:22,y:53,w:56,h:27,r:100,c:'#d1b8f2',a:818},{x:29,y:86,w:42,h:9,r:15,c:'#8960ca',a:950}]:[{x:9,y:11,w:82,h:24,r:26,c:'#faf7fd',a:485},{x:9,y:39,w:82,h:14,r:18,c:'#d1b8f2',a:533},{x:9,y:57,w:38,h:13,r:15,c:'#8960ca',a:582},{x:53,y:57,w:38,h:13,r:15,c:'#b99de0',a:615},{x:9,y:74,w:82,h:16,r:18,c:'#d8c7ed',a:657}])).map((shape,j)=><div key={j} style={{position:'absolute',left:shape.x+'%',top:shape.y+'%',width:shape.w+'%',height:shape.h+'%',borderRadius:shape.r===100?'50%':shape.r*sx,background:shape.c,opacity:clamp((frame-shape.a)/25),transform:shape.r===100?`scale(${.65+.35*clamp((frame-shape.a)/25)})`:undefined}}/>)}</>}<div style={{position:'absolute',top:13*sy,left:'50%',transform:'translateX(-50%)',width:o.notchWidth*sx,height:o.notchHeight*sy,borderRadius:22,background:'black'}}/></div></div>})}</AbsoluteFill>
}
