import React from 'react';
import {AbsoluteFill} from 'remotion';
import motion from './N031-motion.json';
const groups=[
 ['💻 编程语言','JavaScript|TypeScript|Python|Java','Go|Rust|C++|C#|PHP|Ruby','Swift|Kotlin|Scala|HTML/CSS|SQL','Shell|R|MATLAB|Perl|Lua'],
 ['🎨 前端框架','React|Vue|Angular|Next.js|Nuxt','Svelte|Tailwind CSS|Bootstrap','Element UI|Ant Design|Webpack|Vite','Gulp|jQuery|React Native|Flutter'],
 ['⚙ 后端框架','Node.js|Django|Flask|Spring Boot','Express|NestJS|FastAPI|Laravel','Ruby on Rails|Gin|ASP.NET'],
 ['▤ 数据库','MySQL|PostgreSQL|MongoDB','Redis|SQLite|Elasticsearch','Oracle|SQL Server|DynamoDB'],
 ['☁ DevOps / 云服务','Git|Docker|Kubernetes|Jenkins','Linux|CI/CD|AWS|Azure','Google Cloud|阿里云|腾讯云'],
 ['🤝 软技能','团队协作|沟通能力|问题解决|时间管理','学习能力|创新思维|逻辑思维|分析能力','执行力|抗压能力|适应力|责任心','服务意识|领导力|决策能力|谈判技巧','演讲展示|项目管理|需求分析|跨部门协调'],
 ['✏ 设计工具','Photoshop|Illustrator|Figma|Sketch','XD|Axure|Mockplus|Adobe XD','InVision|Blender|After Effects']
];
const selected:Record<string,number>={JavaScript:76,Python:88,Go:112,'团队协作':200,'沟通能力':212,'问题解决':227};
const progress=(f:number,a:number,b:number)=>Math.max(0,Math.min(1,(f-a)/(b-a)));
function Field({label,value}:{label:string;value:string}){return <div style={{flex:1,minWidth:0}}><div style={{fontSize:15,marginBottom:9}}>{label}</div><div style={{height:54,border:'1px solid #d7d7d7',borderRadius:13,background:'white',padding:'15px 17px',boxSizing:'border-box',fontSize:18,whiteSpace:'nowrap'}}>{value}</div></div>}
function Form({f,kind,accent}:{f:number;kind:number;accent:string}){
 const chosen=Object.keys(selected).filter(s=>f>=selected[s]);const result=f>=290;
 return <div style={{position:'absolute',inset:0,background:'#f5f7f8',fontSize:16,color:'#303438'}}>
 <div style={{height:62,padding:'25px 15px 0',background:'white',fontSize:18}}>▣ 简历智造</div><div style={{height:94,background:'white',display:'flex',padding:'25px 10px 0',boxSizing:'border-box',justifyContent:'space-between'}}>{['基本信息','教育背景','工作经历','自我评价','预览导出'].map((s,i)=><div key={s} style={{textAlign:'center',fontSize:12}}><span style={{display:'block',width:33,height:33,borderRadius:'50%',margin:'0 auto 7px',background:i<=kind?accent:'#ddd',color:i<=kind?'white':'#999',fontSize:16,lineHeight:'33px'}}>{i<kind?'✓':i+1}</span>{s}</div>)}</div>
 <div style={{padding:'0 17px',position:'absolute',top:216,left:0,right:0}}>
 {kind===0?<><Field label='性别' value='男'/><div style={{height:24}}/><Field label='手机号' value='13800000000'/><div style={{height:24}}/><Field label='邮箱' value='user@example.invalid'/><div style={{height:24}}/><Field label='所在城市' value='杭州'/><h3>求职意向</h3><Field label='意向岗位' value='新媒体运营'/><div style={{height:20}}/><Field label='期望薪资（可选）' value='8–10K'/></>:<>
 <div style={{fontSize:24,fontWeight:700,textAlign:'center'}}>{kind===1?'教育背景':'工作经历'}</div><div style={{fontSize:16,textAlign:'center',color:'#777',margin:'9px 0 28px'}}>请填写您的{kind===1?'教育经历（可添加多个）':'工作经历和专业技能'}</div>
 {kind===2&&<div style={{background:'#f0edf8',borderRadius:17,padding:17,marginBottom:20}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><b style={{fontSize:17}}>专业技能标签</b><div style={{fontSize:12,color:'#888',marginTop:4}}>选择您的专业技能（最多10个）</div></div><div style={{display:'flex',gap:8,fontSize:14}}><span style={{background:accent,color:'white',padding:'10px 12px',borderRadius:13}}>✧ AI生成</span><span style={{border:`2px solid ${accent}`,color:accent,padding:'8px 10px',borderRadius:12}}>编辑标签</span></div></div><div style={{display:'flex',flexWrap:'wrap',gap:9,marginTop:16}}>{chosen.length?chosen.map(s=><span key={s} style={{fontFamily:'Arial,MiSans',fontSize:14,padding:'6px 10px',background:accent,color:'white',borderRadius:9}}>{s}</span>):<span style={{fontSize:14,color:'#aaa'}}>未选择技能标签</span>}</div></div>}
 {kind===2&&result&&<div style={{border:'1px solid #d5d5d5',background:'white',borderRadius:20,padding:19,marginBottom:20}}><b style={{color:accent,fontSize:17}}>✧ AI生成的技能描述</b><div style={{fontSize:17,lineHeight:1.65,marginTop:13}}>熟练掌握JavaScript、Python、Go、团队协作、沟通能力、问题解决等专业技能，具备扎实的理论基础和丰富的实践经验，能够独立完成相关工作任务，并持续学习和跟进新技术。</div><span style={{display:'inline-block',border:`2px solid ${accent}`,borderRadius:13,color:accent,padding:'8px 14px',marginTop:16}}>查看/编辑</span></div>}
 <div style={{background:'white',border:'1px solid #ddd',borderRadius:18,padding:17}}><div style={{color:accent,marginBottom:22}}>{kind===1?'教育经历 1':'工作经历 1'}<span style={{float:'right'}}>✧　♜</span></div>{kind===1?<><Field label='学校名称' value='北京大学'/><div style={{display:'flex',gap:12,marginTop:20}}><Field label='学历' value='本科'/><Field label='专业' value='传媒'/></div></>:<div style={{display:'flex',gap:12}}><Field label='公司名称' value='自主创业'/><Field label='职位名称' value='程序员'/></div>}<div style={{display:'flex',gap:12,marginTop:20}}><Field label={kind===1?'入学时间':'开始时间'} value={kind===1?'2013年9月':'2017年4月'}/><Field label={kind===1?'毕业时间':'结束时间'} value={kind===1?'2017年6月':'2026年4月'}/></div>{kind===2&&<><div style={{fontSize:15,marginTop:20,marginBottom:10}}>工作描述 / 职责</div><div style={{border:'1px solid #ddd',borderRadius:13,height:100,padding:15,fontSize:16,color:'#aaa'}}>简述您的工作职责和成就…</div></>}</div>
 </>}
 </div></div>;
}
export function SkillsResume({t,accent}:{t:number;accent:string}){
 const f=Math.max(0,Math.min(347,Math.round(t*60))),m=motion[f],modal=progress(f,38,46)*(1-progress(f,255,256));const scroll=m.scroll;
 const phone=(x:number,y:number,scale:number,kind:number)=> <div key={kind} style={{position:'absolute',left:x,top:y,width:490,height:1010,borderRadius:75,background:'#101113',boxShadow:'0 0 0 3px #999',padding:20,boxSizing:'border-box',transform:`scale(${scale})`,transformOrigin:'0 0'}}><div style={{position:'relative',width:450,height:970,borderRadius:57,overflow:'hidden',background:'#f5f7f8'}}><div style={{position:'absolute',inset:0,filter:kind===2&&modal>0?'blur(3px)':undefined,transform:kind===2?`translateY(${-progress(f,320,347)*102/m.scale}px)`:undefined}}><Form f={f} kind={kind} accent={accent}/></div>
 {kind===2&&modal>0&&<><div style={{position:'absolute',inset:0,background:'#0009',opacity:modal}}/><div style={{position:'absolute',left:0,right:0,top:351+(1-modal)*620,height:800,borderRadius:'16px 16px 0 0',background:'white',overflow:'hidden'}}><div style={{height:66,padding:'20px 18px',fontSize:20,fontWeight:600,borderBottom:'1px solid #eee',boxSizing:'border-box'}}>选择专业技能<span style={{float:'right',fontSize:24,color:'#999'}}>×</span></div><div style={{height:730,overflow:'hidden'}}><div style={{padding:'18px 18px',transform:`translateY(${-scroll}px)`}}>{groups.map((group,g)=><div key={group[0]} style={{marginBottom:22}}><div style={{fontSize:16,marginBottom:17}}>{group[0]} <span style={{color:'#aaa',fontSize:14}}>({group.slice(1).join('|').split('|').filter(s=>selected[s]!==undefined&&f>=selected[s]).length}/10)</span></div>{group.slice(1).map((row,i)=><div key={i} style={{display:'flex',gap:9,marginBottom:8}}>{row.split('|').map(s=>{const on=selected[s]!==undefined&&f>=selected[s];return <span key={s} style={{fontFamily:'Arial,MiSans',fontSize:16,fontWeight:500,whiteSpace:'nowrap',padding:'9px 13px',lineHeight:'17px',borderRadius:10,color:on?'white':'#605477',background:on?accent:'#f0edf8'}}>{on?'✓ ':''}{s}</span>})}</div>)}</div>)}</div></div></div></>}
 <div style={{position:'absolute',top:19,left:20,fontSize:18,fontWeight:600}}>12:24</div><div style={{position:'absolute',left:128,top:11,width:188,height:37,background:'#050505',borderRadius:24}}><i style={{position:'absolute',left:12,top:13,width:12,height:12,borderRadius:12,background:accent}}/></div><div style={{position:'absolute',right:22,top:19,fontSize:16}}>▴ ▰</div><div style={{position:'absolute',bottom:25,left:24,right:24,height:46,borderRadius:24,background:'#fffffff2',fontSize:13,display:'flex',alignItems:'center',justifyContent:'space-around'}}>‹　 ▤　 fred.tools/resume　 ↻　 ⋯</div>
 </div></div>;
 return <AbsoluteFill style={{background:'white',fontFamily:'MiSans',fontWeight:400}}>{f<32&&[0,1].map(i=>phone([110,720][i]-m.shift,24,1,i))}{phone(m.x,m.y+progress(f,320,347)*94,m.scale,2)}</AbsoluteFill>;
}
