import {approvedStaticFile as staticFile} from '../material-policy';
import {FiveFontFace} from "../five-fonts.ts";
import React, {useEffect,useState} from 'react';
import {AbsoluteFill, Img, useCurrentFrame, useVideoConfig, delayRender, continueRender, cancelRender} from 'remotion';
import fileData from './files.json';
import {authoredSeconds} from './SceneTiming';
export const accent='#8553d9';
export const clamp=(x:number)=>Math.min(1,Math.max(0,x));
export const lerp=(a:number,b:number,t:number)=>a+(b-a)*t;
export const ease=(t:number)=>{const x=clamp(t);return x*x*(3-2*x)};
export const E=(t:number,a:number,b:number)=>ease((t-a)/(b-a));
export const clock=authoredSeconds;
export const tween=(t:number,points:number[][])=>{if(t<=points[0][0])return points[0][1];for(let i=1;i<points.length;i++){if(t<=points[i][0])return lerp(points[i-1][1],points[i][1],clamp((t-points[i-1][0])/(points[i][0]-points[i-1][0])))}return points[points.length-1][1]};
let fontReady:Promise<unknown>|undefined;
export const Fonts:React.FC=()=>{const [handle]=useState(()=>delayRender('EP103 actual project fonts'));useEffect(()=>{fontReady??=Promise.all([['Medium',500],['Semibold',600],['Bold',700]].map(async([name,weight])=>{const f=await new FiveFontFace('MiSans',`url(${staticFile(`fonts/MiSans-${name}.otf`)})`,{weight:String(weight)}).load();(document.fonts as FontFaceSet & {add:(face:FontFace)=>void}).add(f)}));fontReady=fontReady.then(async()=>{const f=await new FiveFontFace('RuiZi',`url(${staticFile('fonts/RuiZi.ttf')})`).load();(document.fonts as FontFaceSet & {add:(face:FontFace)=>void}).add(f)});fontReady=fontReady.then(async()=>{const f=await new FiveFontFace('OfficialShuHei',`url(${staticFile('fonts/RuiZi.ttf')})`,{weight:'700'}).load();(document.fonts as FontFaceSet & {add:(face:FontFace)=>void}).add(f)});fontReady.then(()=>continueRender(handle)).catch(cancelRender)},[handle]);return null};
export const Base:React.FC<React.PropsWithChildren>=({children})=><AbsoluteFill style={{background:'#fff',color:'#111',fontFamily:'MiSans',fontWeight:700,overflow:'hidden'}}>{children}</AbsoluteFill>;
export const Logo:React.FC<{x?:number;y?:number;size?:number;label?:boolean;opacity?:number;scale?:number}>=({x=1150,y=285,size=240,label=true,opacity=1,scale=1})=><div style={{position:'absolute',left:x,top:y,width:size,opacity,transform:`scale(${scale})`,transformOrigin:'center'}}><Img src={staticFile('doubao-work-approved.png')} style={{width:size,height:size,objectFit:'contain'}}/>{label&&<div style={{fontSize:Math.round(size*.21),whiteSpace:'nowrap',marginTop:22,textAlign:'center'}}>豆包工作</div>}</div>;
export const Pill:React.FC<{text:string;x:number;y:number;w?:number;h?:number;size?:number;opacity?:number;scale?:number;light?:boolean}>=({text,x,y,w=480,h=140,size=60,opacity=1,scale=1,light=false})=><div style={{position:'absolute',left:x,top:y,width:w,height:h,display:'flex',alignItems:'center',justifyContent:'center',background:light?'#fff':'#111',color:light?'#111':'#fff',borderRadius:h/2,fontSize:size,fontWeight:700,boxShadow:light?'0 8px 30px #00000016':'0 14px 28px #00000025',opacity,transform:`scale(${scale})`,whiteSpace:'nowrap'}}>{text}</div>;
const counts:Record<string,number>={step1:408,step2:326,step3:308,member:157,opening:150};
// Cached frames are direct ffmpeg extracts of the four supplied videos, at 30 fps.
export const Recording:React.FC<{source:string;time:number;style?:React.CSSProperties}>=({source,time,style})=>{const n=Math.max(1,Math.min(counts[source],Math.floor(time*30)+1));return <Img src={staticFile(`recordings/${source}/${String(n).padStart(4,'0')}.jpg`)} style={{width:'100%',height:'100%',objectFit:'contain',...style}}/>};
export const Screen:React.FC<{source:string;time:number;x?:number;y?:number;w?:number;h?:number;zoom?:number;ox?:number;oy?:number;opacity?:number;radius?:number}>=({source,time,x=100,y=135,w=1720,h=790,zoom=1,ox=50,oy=50,opacity=1,radius=22})=><div style={{position:'absolute',left:x,top:y,width:w,height:h,overflow:'hidden',borderRadius:radius,boxShadow:'0 18px 48px #00000025,0 0 0 1px #00000013',background:'#fff',opacity}}><Recording source={source} time={time} style={{transform:`scale(${zoom})`,transformOrigin:`${ox}% ${oy}%`}}/></div>;
export const FileObject:React.FC<{index:number;x:number;y:number;scale?:number;rotation?:number;opacity?:number;name?:string;ext?:string}>=({index,x,y,scale=1,rotation=0,opacity=1,name,ext})=>{const f=fileData[index%fileData.length];const e=ext??f.ext;const color:Record<string,string>={PDF:'#dc4339',DOCX:'#2965bd',XLSX:'#258150',MP3:'#8957c7',PPTX:'#d76830'};const c=color[e]??'#777';return <div style={{position:'absolute',left:x-165,top:y-135,width:330,height:270,textAlign:'center',opacity,transform:`scale(${scale}) rotate(${rotation}deg)`}}><svg width="124" height="158" viewBox="0 0 124 158" style={{filter:'drop-shadow(0 8px 9px #0002)'}}><path d="M12 2H83L120 39V146Q120 155 111 155H12Q3 155 3 146V11Q3 2 12 2Z" fill="#fff" stroke="#d5d5d5" strokeWidth="2"/><path d="M82 2V31Q82 40 91 40H120" fill="#eaeaea"/><rect x="0" y="53" width="85" height="46" rx="7" fill={c}/><text x="42" y="85" textAnchor="middle" fill="white" fontFamily="Arial" fontWeight="700" fontSize="24">{e==='DOCX'?'W':e==='XLSX'?'X':e==='MP3'?'♫':e}</text>{[115,127,139].map(y=><path key={y} d={`M21 ${y}H100`} stroke="#ddd" strokeWidth="4"/>)}</svg><div style={{fontSize:24,fontWeight:600,lineHeight:1.4,marginTop:12,overflowWrap:'anywhere',textShadow:'0 1px 3px #fff'}}>{name??f.name}</div></div>};
// The visible file identity is always real. Layout is episode-specific, anchored to N038.
export const FileCloud:React.FC<{t:number;settled?:boolean}>=({t,settled=false})=>{const spread=settled?1:E(t,5.6,6.65);return <>{fileData.slice(0,30).map((f,i)=>{const a=E(t,.15+i*.065,.55+i*.065);const col=i%6,row=Math.floor(i/6);const bx=275+col*270+Math.sin(i*3)*64,by=175+row*153+Math.cos(i*4)*30;const dx=bx-960,dy=by-510;const multiplier=lerp(1,1.98,spread);return <FileObject key={i} index={i} x={960+dx*multiplier+(1-a)*(i%2?750:-750)} y={510+dy*multiplier-(1-a)*230} scale={lerp(.55,.79,a)*(i<6?1:.92)} rotation={lerp(i%2?18:-18,Math.sin(i*12)*9,a)} opacity={a*lerp(1,.48,spread)}/>})}</>};
