import React from 'react';
import {AbsoluteFill,Img,staticFile,useCurrentFrame} from 'remotion';
import {measuredSample} from './RebuiltGrid';
import {PromptFocus} from './RebuiltT07';
import spec from '../../../../specs/W05.json';

export const PhoneUI:React.FC<{index:number}>=({index})=>{const card=spec.objects.cards[index],ui=card.ui;const ink='#151419',purple='#8960ca';
 const chip=(text:string)=><div style={{background:ink,color:'white',borderRadius:10,padding:'13px 12px',textAlign:'center',fontSize:18,fontWeight:800}}>{text}</div>;
 const row=(title:string,sub:string)=><div style={{borderRadius:12,background:'#f3f2f5',padding:14,marginBottom:13,display:'flex',gap:12,alignItems:'center'}}><div style={{width:54,height:60,borderRadius:9,background:'#e5dcf1',display:'grid',placeItems:'center',color:purple,fontSize:27}}>≋</div><div style={{flex:1}}><b style={{fontSize:19}}>{title}</b><div style={{fontSize:13,color:'#777',marginTop:7}}>{sub}</div></div><span style={{fontSize:20}}>＋</span></div>;
 return <div style={{width:card.rect[2],height:922,background:'white',fontFamily:'CTWHeavy',color:ink,fontWeight:500,fontSize:18,position:'relative',overflow:'hidden'}}>
  <div style={{height:37,padding:'11px 21px 0',boxSizing:'border-box',display:'flex',justifyContent:'space-between',fontSize:12,background:index===0?ink:'white',color:index===0?'white':ink}}><b>9:41</b><span>▴ ▰ ●</span></div>
  {index===0?<><div style={{height:286,background:ink,color:'white',padding:'142px 30px 20px',boxSizing:'border-box'}}><div style={{fontSize:12,letterSpacing:3,color:'#b3a9be'}}>FREDTALK</div><div style={{fontSize:48,fontWeight:900}}>{ui.title}</div><div style={{fontSize:13,marginTop:9,color:'#c6bccf'}}>{ui.subtitle}</div></div><div style={{padding:'27px 27px'}}><h3 style={{fontSize:22,margin:'0 0 24px'}}>{ui.heading}</h3>{['邮箱地址','密码'].map((t,i)=><div key={t} style={{marginBottom:20}}><div style={{fontSize:13,marginBottom:9}}>{t}</div><div style={{background:'#f4f4f4',height:44,borderRadius:9,padding:'13px',boxSizing:'border-box',color:'#a8a5ad',fontSize:12}}>{i?'输入密码':'输入邮箱地址'}</div></div>)}<div style={{fontSize:12,textDecoration:'underline',marginBottom:15}}>忘记密码？</div>{chip('登录')}<div style={{textAlign:'center',fontSize:12,color:'#aaa',margin:'25px 0'}}>或使用其他方式</div><div style={{border:'1px solid #ddd',borderRadius:10,padding:13,textAlign:'center',fontSize:15}}>继续使用已有账号</div><p style={{fontSize:12,textAlign:'center',color:'#777',marginTop:27}}>新用户？创建账号</p></div></>:
  <div style={{padding:'12px 23px'}}><header style={{display:'flex',justifyContent:'space-between',alignItems:'center',fontSize:13,marginBottom:22}}><b>{index===1?'FREDTALK':'‹'}</b><span>{index===1?'＋':ui.title}</span><span>◯</span></header>
   {index===1?<><div style={{background:'#f3f3f5',padding:13,borderRadius:12,fontSize:13,color:'#999'}}>搜索记录</div><div style={{background:ink,color:'white',borderRadius:14,padding:'20px 16px',margin:'18px 0'}}><div style={{fontSize:12,color:'#d2c1e7'}}>本周记录</div><div style={{fontSize:23,fontWeight:900,whiteSpace:'nowrap',margin:'7px 0'}}>让灵感随时留下</div><div style={{color:'#cdb8fa',fontSize:27,letterSpacing:4}}>▁▃▅▂▆▃▅▁▃▆</div></div><h3 style={{fontSize:20}}>快速开始</h3><div style={{display:'flex',gap:10,marginBottom:24}}>{['录音','导入','整理','回顾'].map(t=><div key={t} style={{flex:1,background:'#f3f3f5',borderRadius:10,padding:'15px 0',textAlign:'center',fontSize:13}}><b style={{display:'block',fontSize:22,color:purple,marginBottom:6}}>◉</b>{t}</div>)}</div><h3 style={{fontSize:20}}>{ui.heading}</h3><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:13}}>{['产品方案','选题灵感','团队讨论','每日回顾'].map((t,i)=><div key={t}><div style={{height:113,borderRadius:12,background:['#e5dfec','#eee9de','#dedfe7','#e9deed'][i],display:'grid',placeItems:'center',color:purple,fontSize:44}}>≋</div><b style={{fontSize:15,display:'block',marginTop:8}}>{t}</b><small style={{fontSize:11,color:'#888'}}>今日 · 已整理</small></div>)}</div></>:
   index===2?<><div style={{height:268,background:'#f5f5f5',borderRadius:12,display:'grid',placeItems:'center'}}><Img src={staticFile('clean/product.png')} style={{width:'88%',height:'88%',objectFit:'contain'}}/></div><small style={{fontSize:12,color:'#777',display:'block',marginTop:20}}>{ui.subtitle}</small><h3 style={{fontSize:24,margin:'10px 0'}}>产品方案讨论</h3><b style={{fontSize:21}}>23 分 18 秒</b><p style={{fontSize:13,color:'#777'}}>今天 09:30 · 音频记录</p><div style={{borderTop:'1px solid #eee',paddingTop:17,fontSize:13,lineHeight:1.9}}>讨论新一轮产品方案，梳理需求与后续行动。保留录音，方便随时回顾。</div><div style={{display:'flex',gap:10,margin:'25px 0'}}>{['逐字稿','摘要','待办'].map(t=><span key={t} style={{padding:'10px 14px',background:'#eee',borderRadius:9,fontSize:12}}>{t}</span>)}</div><div style={{fontSize:14,lineHeight:2.2}}>负责人：Fred<br/>状态：已整理<br/>来源：会议录音</div></>:
   <><h2 style={{fontSize:30,margin:'10px 0 26px'}}>{ui.title}</h2>{row('产品方案讨论','23:18 · 今日 09:30')}{row('团队同步会议','18:42 · 昨日 14:00')}<div style={{margin:'25px 0',padding:'15px',background:'#f3f2f5',borderRadius:10,fontSize:13}}>整理方式 <b style={{float:'right'}}>会议纪要</b></div><div style={{fontSize:13,lineHeight:2.4,color:'#777'}}>选中记录 <span style={{float:'right',color:ink}}>2 条</span><br/>录音时长 <span style={{float:'right',color:ink}}>42 分钟</span><br/>输出内容 <span style={{float:'right',color:ink}}>摘要 · 待办</span></div><div style={{borderTop:'1px solid #ddd',marginTop:22,paddingTop:20,display:'flex',justifyContent:'space-between',fontWeight:900}}>合计<span>2 条记录</span></div></>}
   <div style={{position:'absolute',left:23,right:23,bottom:38}}>{chip(index===1?'＋ 新建记录':index===2?'开始回顾':'开始整理')}</div>
  </div>}<div style={{position:'absolute',bottom:9,left:(card.rect[2]-90)/2,width:90,height:5,borderRadius:4,background:ink}}/>
 </div>};

export const RebuiltW05:React.FC<{referenceWords?:boolean}>=({referenceWords=false})=>{const f=useCurrentFrame();if(f>=45)return <PromptFocus data={spec} frame={f} referenceWords={referenceWords}/>;const blur=measuredSample(spec.tracks,'firstBlur',f)[0];return <AbsoluteFill style={{background:'white'}}><AbsoluteFill style={{filter:`blur(${blur}px)`}}>{spec.objects.cards.map((card,i)=>{const[x,y,w,h]=card.rect;return <div key={i} style={{position:'absolute',left:x,top:y,width:w,height:h,borderRadius:card.radius,boxShadow:'28px 17px 24px #0004',overflow:'hidden'}}><div style={{transform:`scale(${w/card.rect[2]},${h/922})`,transformOrigin:'0 0'}}><PhoneUI index={i}/></div></div>})}</AbsoluteFill>{spec.objects.foreground.map((word,i)=><div key={i} style={{position:'absolute',left:word.x,top:word.y,width:word.width,fontFamily:'CTWHeavy',fontWeight:900,fontSize:word.fontSize,color:referenceWords?'#cede69':'#CDB8FA',textAlign:'center',whiteSpace:'nowrap',textShadow:'6px 8px 12px #0008',opacity:measuredSample(spec.tracks,word.track,f)[0]}}>{referenceWords?word.referenceText:word.text}</div>)}</AbsoluteFill>};
