import {useCurrentFrame} from 'remotion';
import type {V7Spec} from './types';
import {Conclusion,FixedReveal,Headline,reveal,Surface,V7Canvas,V7Sfx} from './V7Shared';

const lines=(count:number)=><div style={{position:'absolute',inset:'72px 70px',display:'flex',flexDirection:'column',gap:28}}>{Array.from({length:count},(_,i)=><div key={i} style={{height:i===0?48:30,width:i===count-1?'62%':i===0?'48%':'100%',borderRadius:30,background:i===0?'#111':'#c9c9c6'}}/>)}</div>;

export const V7MediaStages=({spec}:{spec:V7Spec})=>{
  const f=useCurrentFrame();const [a,b,c,d]=spec.cues;const dark=spec.background==='black';
  if(spec.layout==='single-stage-focus') return <V7Canvas dark={false}><FixedReveal at={a} from="center"><Headline>{spec.words[0]}</Headline></FixedReveal><FixedReveal at={b} from="right"><Surface dark style={{left:250,top:275,width:1420,height:610,display:'flex',alignItems:'center',justifyContent:'center',fontSize:144,fontWeight:600}}>{spec.words[1]}</Surface></FixedReveal><V7Sfx spec={spec}/></V7Canvas>;
  if(spec.layout==='fixed-input-panel'||spec.layout==='prompt-panel') return <V7Canvas dark={false}><Headline style={{top:96}}>{spec.words[0]}</Headline><FixedReveal at={a} from="center"><Surface style={{left:260,top:310,width:1400,height:380,display:'flex',alignItems:'center',justifyContent:'center'}}><div style={{width:1050,height:116,borderRadius:58,background:'#111'}}/></Surface></FixedReveal><FixedReveal at={b} from="center"><Conclusion>{spec.words[1]}</Conclusion></FixedReveal><V7Sfx spec={spec}/></V7Canvas>;
  if(spec.layout==='fixed-cascade') {const active=Math.max(0,Math.min(2,Math.floor((f-a)/68)));return <V7Canvas dark>{spec.words.slice(0,3).map((w,i)=><FixedReveal key={w} at={[a,b,c][i]??a} from="left"><Surface dark={i!==active} style={{left:180+i*515,top:270,width:500,height:520,background:i===active?'#fff':'#151515',color:i===active?'#090909':'#777',display:'flex',alignItems:'center',justifyContent:'center',fontSize:104,fontWeight:600}}>{w}</Surface></FixedReveal>)}<V7Sfx spec={spec}/></V7Canvas>}
  if(spec.layout==='fixed-document-pair'||spec.layout==='paired-docs') return <V7Canvas dark={false}><Headline style={{top:72,fontSize:82}}>{spec.words[0]}</Headline><FixedReveal at={a}><Surface style={{left:180,top:250,width:740,height:620}}>{lines(7)}</Surface></FixedReveal><FixedReveal at={b} from="right"><Surface style={{right:180,top:250,width:740,height:620}}>{lines(5)}</Surface></FixedReveal><FixedReveal at={c??b} from="center"><Conclusion style={{bottom:68,fontSize:78}}>{spec.words[1]}</Conclusion></FixedReveal><V7Sfx spec={spec}/></V7Canvas>;
  if(spec.layout==='fixed-dark-window') return <V7Canvas dark={false}><FixedReveal at={a} from="center"><Surface dark style={{left:170,top:135,width:1580,height:810}}><FixedReveal at={b} from="center"><Headline dark style={{top:150,fontSize:86}}>{spec.words[0]}</Headline></FixedReveal><FixedReveal at={c} from="center"><Conclusion dark style={{bottom:170,fontSize:128}}>{spec.words[1]}</Conclusion></FixedReveal></Surface></FixedReveal><V7Sfx spec={spec}/></V7Canvas>;
  if(spec.layout==='single-media-focus') return <V7Canvas dark={false}><Headline style={{top:78}}>{spec.words[0]}</Headline><div style={{position:'absolute',left:170,right:170,top:260,bottom:145}}>{[0,1,2].map(i=><Surface key={i} style={{left:i*72,top:i*30,width:1180,height:580,background:i===2?'#101010':'#e9e9e7',boxShadow:i===2?'0 34px 78px rgba(0,0,0,.3)':'none'}}/>)}<FixedReveal at={b} from="right" style={{position:'absolute',left:430,top:145,width:760,height:290,display:'flex',alignItems:'center',justifyContent:'center',color:'#fff',fontSize:100,fontWeight:600,textAlign:'center'}}>{spec.words[1]}</FixedReveal></div><V7Sfx spec={spec}/></V7Canvas>;
  if(spec.layout==='fixed-browser-stage') return <V7Canvas dark={false}><Headline style={{top:70,fontSize:88}}>{spec.words[0]}</Headline><FixedReveal at={a} from="center"><Surface dark style={{left:230,top:265,width:1460,height:590}}><div style={{position:'absolute',left:90,right:90,top:90,bottom:90,display:'grid',gridTemplateColumns:'1fr 1fr',gap:36}}><div style={{background:'#202020',borderRadius:24}}/><div style={{background:'#fff',borderRadius:24,display:'flex',alignItems:'center',justifyContent:'center',color:'#090909',fontSize:82,fontWeight:600,textAlign:'center',padding:50}}>{spec.words[1]}</div></div></Surface></FixedReveal><V7Sfx spec={spec}/></V7Canvas>;
  if(spec.layout==='single-card-conclusion') return <V7Canvas dark={false}><FixedReveal at={a} from="center"><Surface style={{left:330,top:140,width:1260,height:540,display:'flex',alignItems:'center',justifyContent:'center',fontSize:112,fontWeight:600}}>{spec.words[0]}</Surface></FixedReveal><FixedReveal at={b} from="center"><Conclusion style={{bottom:115,fontSize:102}}>{spec.words[1]}</Conclusion></FixedReveal><V7Sfx spec={spec}/></V7Canvas>;
  const p=reveal(f,a);return <V7Canvas dark><Surface dark style={{left:145,top:155,width:1630,height:770,clipPath:`inset(0 ${(1-p)*50}%)`}}><Headline dark style={{top:180,fontSize:90}}>{spec.words[0]}</Headline><FixedReveal at={b} from="center"><Conclusion dark style={{bottom:200,fontSize:132}}>{spec.words[1]}</Conclusion></FixedReveal></Surface><V7Sfx spec={spec}/></V7Canvas>;
};
