import {useCurrentFrame} from 'remotion';
import type {V7Spec} from './types';
import {Conclusion,fill,FixedReveal,Headline,ink,reveal,V7Canvas,V7Sfx} from './V7Shared';

export const V7ResultStages=({spec}:{spec:V7Spec})=>{
  const f=useCurrentFrame();const [a,b,c,d,e]=spec.cues;const dark=spec.background==='black';
  if(spec.layout==='fixed-result-board') return <V7Canvas dark>{spec.words.slice(0,3).map((w,i)=><FixedReveal key={w} at={[a,b,c][i]??a} style={{position:'absolute',left:90+i*610,top:120,width:560,height:300,borderRadius:28,background:'#171717',display:'flex',alignItems:'center',justifyContent:'center',fontSize:72,fontWeight:600,textAlign:'center',padding:45}}>{w}</FixedReveal>)}<FixedReveal at={d} from="center"><div style={{position:'absolute',left:120,right:120,bottom:110,height:430,borderRadius:30,background:'#fff',color:'#090909',display:'flex',alignItems:'center',justifyContent:'center',fontSize:132,fontWeight:600}}>{spec.words[3]}</div></FixedReveal><V7Sfx spec={spec}/></V7Canvas>;
  if(spec.layout==='metric-ribbon') {const active=Math.max(0,Math.min(2,Math.floor((f-a)/68)));return <V7Canvas dark={false}><div style={{position:'absolute',left:125,right:125,top:250,height:580,display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:20}}>{spec.words.map((w,i)=><div key={w} style={{borderRadius:28,background:fill(i<=active,false),color:ink(i<=active,false),display:'flex',alignItems:'center',justifyContent:'center',fontSize:132,fontWeight:600,clipPath:`inset(0 ${(1-reveal(f,[a,b,c][i]??a))*100}% 0 0)`}}>{w}</div>)}</div><V7Sfx spec={spec}/></V7Canvas>}
  const active=Math.max(0,Math.min(spec.words.length-1,Math.floor((f-a)/62)));return <V7Canvas dark={dark}><Headline dark={dark} style={{top:75,fontSize:82}}>{spec.words[0]}</Headline><div style={{position:'absolute',left:150,right:150,top:290,bottom:150,display:'grid',gridTemplateColumns:`repeat(${Math.min(4,spec.words.length)},1fr)`,gap:20}}>{spec.words.map((w,i)=><div key={w} style={{borderRadius:28,background:fill(i<=active,dark),color:ink(i<=active,dark),display:'flex',alignItems:'center',justifyContent:'center',fontSize:spec.words.length>3?66:96,fontWeight:600,textAlign:'center',padding:36,clipPath:`inset(0 ${(1-reveal(f,[a,b,c,d,e][i]??a))*100}% 0 0)`}}>{w}</div>)}</div><Conclusion dark={dark} style={{bottom:54,fontSize:70}}>{spec.words.at(-1)}</Conclusion><V7Sfx spec={spec}/></V7Canvas>;
};

