import {useCurrentFrame} from 'remotion';
import type {V7Spec} from './types';
import {Conclusion,fill,FixedReveal,Headline,ink,reveal,V7Canvas,V7Sfx} from './V7Shared';

export const V7TypeStages=({spec}:{spec:V7Spec})=>{
  const f=useCurrentFrame();const [a,b,c,d,e]=spec.cues;const dark=spec.background==='black';
  if(spec.layout==='fixed-split-copy') return <V7Canvas dark><FixedReveal at={a} style={{position:'absolute',left:120,top:185,width:780,height:710,background:'#fff',color:'#090909',display:'flex',alignItems:'center',justifyContent:'center',fontSize:106,fontWeight:600,lineHeight:1.08,textAlign:'center',padding:80}}>{spec.words[0]}</FixedReveal><FixedReveal at={b} from="right" style={{position:'absolute',right:120,top:185,width:780,height:710,display:'flex',alignItems:'center',justifyContent:'center',fontSize:118,fontWeight:600,lineHeight:1.08,textAlign:'center',padding:80}}>{spec.words[1]}</FixedReveal><V7Sfx spec={spec}/></V7Canvas>;
  if(spec.layout==='hard-cut-contrast') {const swap=f>=b;return <V7Canvas dark={swap}><div style={{position:'absolute',inset:0,display:'flex',alignItems:'center',justifyContent:'center',fontSize:176,fontWeight:600,letterSpacing:-6}}>{swap?spec.words[1]:spec.words[0]}</div><V7Sfx spec={spec}/></V7Canvas>;}
  if(spec.layout==='fixed-word-grid') return <V7Canvas dark={false}><div style={{position:'absolute',left:150,right:150,top:130,bottom:130,display:'grid',gridTemplateColumns:'1fr 1fr',gridTemplateRows:'1fr 1fr',gap:24}}>{spec.words.map((w,i)=>{const p=reveal(f,[a,b,c,d][i]??a);return <div key={w} style={{background:i%2?'#090909':'#f1f1ef',color:i%2?'#fff':'#090909',display:'flex',alignItems:'center',justifyContent:'center',fontSize:126,fontWeight:600,clipPath:`inset(0 ${(1-p)*100}% 0 0)`,borderRadius:28}}>{w}</div>})}</div><V7Sfx spec={spec}/></V7Canvas>;
  if(spec.layout==='fixed-counter-slot'){const run=Math.max(0,Math.min(1,(f-b)/96));const value=Math.max(1,Math.round(100*Math.pow(.01,run)));return <V7Canvas dark><div style={{position:'absolute',left:240,right:240,top:104,height:730,display:'flex',alignItems:'center',justifyContent:'center',fontFamily:'SF Pro Display,-apple-system,MiSans,sans-serif',fontSize:520,fontWeight:600,letterSpacing:-28}}>{value}</div><FixedReveal at={c} from="center" style={{position:'absolute',left:0,right:0,bottom:82,textAlign:'center',fontSize:78,fontWeight:500}}>越来越快</FixedReveal><V7Sfx spec={spec}/></V7Canvas>}
  if(spec.layout==='fixed-word-impact') return <V7Canvas dark={false}><FixedReveal at={a} style={{position:'absolute',left:190,top:82,width:720,height:760,display:'flex',alignItems:'center',justifyContent:'center',fontSize:520,fontWeight:600,letterSpacing:-30}}>{spec.words[0]}</FixedReveal><FixedReveal at={b} from="right" style={{position:'absolute',right:140,top:300,width:920,height:430,background:'#090909',color:'#fff',borderRadius:30,display:'flex',alignItems:'center',justifyContent:'center',fontSize:132,fontWeight:600}}>{spec.words[1]}</FixedReveal><V7Sfx spec={spec}/></V7Canvas>;
  if(spec.layout==='fixed-three-column'||spec.layout==='dark-word-sequence') {const words=spec.words.slice(0,3);const active=Math.max(0,Math.min(2,Math.floor((f-(b??a))/68)));return <V7Canvas dark><div style={{position:'absolute',left:125,right:125,top:190,bottom:190,display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:22}}>{words.map((w,i)=><div key={w} style={{borderRadius:28,background:fill(i<=active,true),color:ink(i<=active,true),display:'flex',alignItems:'center',justifyContent:'center',fontSize:112,fontWeight:600,clipPath:`inset(0 ${(1-reveal(f,[a,b,c][i]??a))*100}% 0 0)`}}>{w}</div>)}</div><V7Sfx spec={spec}/></V7Canvas>}
  if(spec.layout==='fixed-word-pair') {const second=f>=b;return <V7Canvas dark><div style={{position:'absolute',left:160,right:160,top:176,bottom:176,display:'grid',gridTemplateColumns:'1fr 1fr',gap:30}}>{spec.words.map((w,i)=><div key={w} style={{borderRadius:30,background:fill(second?i===1:i===0,true),color:ink(second?i===1:i===0,true),display:'flex',alignItems:'center',justifyContent:'center',fontSize:106,fontWeight:600,textAlign:'center'}}>{w}</div>)}</div><V7Sfx spec={spec}/></V7Canvas>}
  return <V7Canvas dark><FixedReveal at={a} from="center"><Headline dark style={{top:250,height:180,fontSize:148}}>{spec.words[0]}</Headline></FixedReveal><FixedReveal at={b} from="center"><Conclusion dark style={{bottom:250,minHeight:180,fontSize:142}}>{spec.words[1]}</Conclusion></FixedReveal><V7Sfx spec={spec}/></V7Canvas>;
};

