import React from 'react';
import {AbsoluteFill,Freeze,Img,OffthreadVideo,staticFile,interpolate,Easing} from 'remotion';
import manifest from '../manifest.json';
export const B='#111',W='#fff',P='#bda4fa';
export const q=(t:number,a:number,b:number)=>interpolate(t,[a,b],[0,1],{easing:Easing.bezier(.16,1,.3,1),extrapolateLeft:'clamp',extrapolateRight:'clamp'});
export const lin=(t:number,a:number,b:number)=>Math.max(0,Math.min(1,(t-a)/(b-a)));
export const mix=(a:number,b:number,p:number)=>a+(b-a)*p;
export const copy=(id:string)=>(manifest.revisionCopy as any)[id] as string[];
export const old=(id:string)=>manifest.pages.find(p=>p.stableId==='ep93-'+id)!.exactScreenWords;
export const Txt=({x=0,y=0,w=1920,size=72,children,style={}}:any)=><div style={{position:'absolute',left:x,top:y,width:w,fontSize:size,fontWeight:600,lineHeight:1.3,...style}}>{children}</div>;
export const Surface=({x=0,y=0,w=1000,h=600,dark=false,children,style={}}:any)=><div style={{position:'absolute',left:x,top:y,width:w,height:h,background:dark?B:W,color:dark?W:B,borderRadius:26,overflow:'hidden',boxShadow:'0 20px 60px #00000016',...style}}>{children}</div>;
export const Enter=({t,at,children,style={}}:any)=><div style={{position:'absolute',inset:0,clipPath:`inset(${100*(1-q(t,at,at+.45))}% 0 0 0)`,...style}}>{children}</div>;
export const Char=({t,at,name,x=100,y=180,h=720,startFrame=1}:any)=>{const f=Math.max(1,Math.min(150,Math.floor((t-at)*30)+startFrame));return <Img src={staticFile(`characters/${name}/frame-${String(f).padStart(3,'0')}.png`)} style={{position:'absolute',left:x,top:y,height:h,transform:`translateY(${140*(1-q(t,at,at+.45))}px)`}}/>};
export const Recording=({file,t,at,start=0,length=10,speed=1,x=200,y=250,w=1400,h=550}:any)=><Surface x={x} y={y} w={w} h={h} style={{padding:8,boxSizing:'border-box',borderRadius:22}}><Freeze frame={Math.max(0,Math.min(Math.floor((start+length)*60)-1,Math.floor(((t-at)*speed+start)*60)))}><OffthreadVideo muted src={staticFile(file+'.mp4')} style={{width:'100%',height:'100%',objectFit:'contain'}}/></Freeze></Surface>;
export const Window=({children,x=160,y=175,w=1600,h=710,dark=true,style={}}:any)=><Surface x={x} y={y} w={w} h={h} dark={dark} style={style}><div style={{height:60,background:dark?'#080808':'#eee',display:'flex',gap:13,alignItems:'center',paddingLeft:26}}>{['#ff5f57','#febc2e','#28c840'].map(c=><i key={c} style={{width:13,height:13,borderRadius:20,background:c}}/>)}</div><div style={{position:'absolute',left:0,right:0,top:60,bottom:0,overflow:'hidden'}}>{children}</div></Surface>;
// Approved WordGrid: retained 2x2 geometry, left-origin fill and text entry; content/timing adapted.
export const WordGrid=({items,t,at,x=160,y=175,w=1600,h=710,step=.55}:any)=><Window x={x} y={y} w={w} h={h}><div style={{position:'absolute',inset:'40px 58px',display:'grid',gridTemplateColumns:'1fr 1fr',gridTemplateRows:'1fr 1fr',gap:14}}>{items.map((word:string,i:number)=>{const p=q(t,at+i*step,at+i*step+.34);return <div key={word} style={{position:'relative',borderRadius:20,overflow:'hidden',background:'#222328',display:'grid',placeItems:'center'}}><div style={{position:'absolute',inset:0,background:'#303137',transformOrigin:'left',transform:`scaleX(${p})`}}/><div style={{position:'relative',color:W,fontSize:Math.min(82,w*.06),fontWeight:600,transform:`translateX(${-40*(1-p)}px)`,clipPath:`inset(0 ${100*(1-p)}% 0 0)`}}>{word}</div></div>})}</div></Window>;
export const Focus=({t,at,text,sub='',dark=false}:any)=>{const p=q(t,at,at+.42);return <div style={{position:'absolute',inset:0,background:dark?'#111e':'#fffffff2',backdropFilter:`blur(${16*p}px)`,clipPath:`inset(${50*(1-p)}% 0)`,display:'flex',flexDirection:'column',justifyContent:'center',alignItems:'center',paddingBottom:100,color:dark?W:B}}><div style={{fontSize:112,fontWeight:600,transform:`translateY(${80*(1-p)}px)`}}>{text}</div>{sub&&<div style={{fontSize:55,marginTop:50}}>{sub}</div>}</div>};

export const Frost=({t,at,text,sub='',dark=false}:any)=>{const p=q(t,at,at+.6);return <div style={{position:'absolute',inset:0,background:dark?`rgba(12,12,14,${.62*p})`:`rgba(255,255,255,${.58*p})`,backdropFilter:`blur(${20*p}px)`,color:dark?W:B,display:'flex',flexDirection:'column',justifyContent:'center',alignItems:'center',paddingBottom:100}}><div style={{fontSize:106,fontWeight:600,transform:`translateY(${35*(1-p)}px)`}}>{text}</div>{sub&&<div style={{fontSize:58,fontWeight:600,marginTop:44}}>{sub}</div>}</div>};

export const TextHandoff=({t,at,before,after,size=106}:any)=>{const p=q(t,at,at+.55);return <div style={{position:'relative',height:size*1.4,width:1600,overflow:'hidden',textAlign:'center',fontSize:size,fontWeight:600}}><div style={{position:'absolute',inset:0,transform:`translateY(${-size*1.5*p}px)`}}>{before}</div><div style={{position:'absolute',inset:0,transform:`translateY(${size*1.5*(1-p)}px)`}}>{after}</div></div>};
