import {approvedStaticFile as staticFile} from '../material-policy';
import React,{useEffect,useRef,useState} from 'react';
import {AbsoluteFill, delayRender, continueRender} from 'remotion';
import {q,mix} from './UI';
export function FullPrompt({c,t}:any){
 const measure=useRef<HTMLDivElement>(null);const [bounds,setBounds]=useState<any[]>([]);const [handle]=useState(()=>delayRender('Measure complete prompt emphasis'));
 const words=c.prompt.fullText.replace(/\\n/g,'\n');const hits=c.fullPromptHighlights;const dark=c.promptStyle==='black-glass',desk=c.promptStyle==='workbench',draft=c.promptStyle==='drafting';
 const fs=28,lh=1.65,innerWidth=desk?1516:1576,inset=desk?32:2;const textStyle:React.CSSProperties={fontSize:fs,lineHeight:lh,fontWeight:500,whiteSpace:'pre-wrap',padding:'34px 46px',color:dark?'#f4f4f5':'#30313a'};
 const rich=(live:boolean)=>{let pos=0;const nodes:React.ReactNode[]=[];hits.map((h:any,i:number)=>({...h,i,index:words.indexOf(h.text)})).sort((a:any,b:any)=>a.index-b.index).forEach((h:any)=>{nodes.push(words.slice(pos,h.index));nodes.push(<span key={h.i} data-focus={h.i} style={{display:'inline-block',whiteSpace:'nowrap',...(live?{backgroundImage:`linear-gradient(${dark?'#75529e':'#c7aaff'},${dark?'#75529e':'#c7aaff'})`,backgroundSize:`${q(t,h.at,h.at+h.duration)*100}% 100%`,backgroundRepeat:'no-repeat',boxDecorationBreak:'clone',WebkitBoxDecorationBreak:'clone',borderRadius:3}:{})}}>{h.text}</span>);pos=h.index+h.text.length});nodes.push(words.slice(pos));return nodes};
 useEffect(()=>{let active=true;(async()=>{const font=new FontFace('MiSans',`url(${staticFile('Medium.otf')})`,{weight:'500'});await font.load();document.fonts.add(font);await new Promise<void>(r=>requestAnimationFrame(()=>r()));if(!active)return;const root=measure.current!;const base=root.getBoundingClientRect();const ratio=base.width/innerWidth;if(root.scrollHeight>720)throw new Error(`Full prompt exceeds carrier: ${c.id}, ${root.scrollHeight}`);const boxes=hits.map((_:any,i:number)=>{const el=root.querySelector(`[data-focus="${i}"]`)!;const rects=Array.from(el.getClientRects());const b=rects[0];return {x:(b.left-base.left)/ratio+170+inset,y:(b.top-base.top)/ratio+95+inset,w:b.width/ratio,h:b.height/ratio}});setBounds(boxes);continueRender(handle)})();return()=>{active=false}},[c.id]);
 const [start,end]=c.promptWindow;const enter=q(t,start,start+.5),exit=q(t,end,end+.5);
 let scale=1,tx=0,ty=0;hits.forEach((h:any,i:number)=>{const b=bounds[i];if(!b)return;const p=q(t,h.at,h.at+.55),z=Math.min(1.8,1400/Math.max(600,b.w));scale=mix(scale,z,p);tx=mix(tx,960-(b.x+b.w/2)*z,p);ty=mix(ty,370-(b.y+b.h/2)*z,p)});
 const shell:React.CSSProperties={position:'absolute',left:170,top:95,width:1580,height:780,borderRadius:desk?34:dark?42:draft?12:26,boxSizing:'border-box',padding:desk?30:0,background:desk?'#090a0c':dark?'rgba(12,14,20,.96)':'rgba(255,255,255,.85)',border:dark||desk?'2px solid #ffffff28':'2px solid #fff',boxShadow:'0 22px 65px #15202c21',overflow:'hidden',backdropFilter:'blur(30px)'};
 return <><div ref={measure} style={{position:'absolute',left:0,top:0,width:innerWidth,visibility:'hidden',...textStyle,boxSizing:'border-box'}}>{rich(false)}</div>{t>=start&&t<end+.5&&<AbsoluteFill><AbsoluteFill style={{background:`rgba(255,255,255,${.25*enter*(1-exit)})`}}/><div style={{...shell,transform:`translate(${tx}px,${ty+950*(1-enter)-1300*exit}px) scale(${scale})`,transformOrigin:'-170px -95px'}}><div style={{height:'100%',boxSizing:'border-box',overflow:'hidden',borderRadius:desk?12:0,background:desk?'#f9fafb':'transparent'}}><div style={textStyle}>{rich(true)}</div></div></div></AbsoluteFill>}</>;
}
