import {approvedStaticFile as staticFile} from '../material-policy';
import React from 'react';
import {AbsoluteFill, Img, interpolate} from 'remotion';
import type {Overrides} from './index';
import cues from './timelines/X015.json';
const val=(f:number,p:number[][])=>interpolate(f,p.map(v=>v[0]),p.map(v=>v[1]),{extrapolateLeft:'clamp',extrapolateRight:'clamp'});
function Poster({kind,product,room,accent,title}:{kind:number;product:string;room:string;accent:string;title:string}){
 const pic=(style:React.CSSProperties={})=><Img src={product} style={{width:'100%',height:'100%',objectFit:'contain',filter:'grayscale(1)',...style}}/>;
 const heading=<div style={{position:'absolute',left:25,right:25,top:55,fontSize:kind===0?52:39,lineHeight:1.2,fontWeight:900,textAlign:'center',zIndex:2}}>{title}</div>;
 if(kind===0)return <AbsoluteFill style={{background:'#f0eff2'}}>{heading}<div style={{position:'absolute',top:145,left:30,right:30,display:'flex',gap:12}}>{['即时记录','清晰表达','专注创作'].map(s=><span key={s} style={{fontSize:21,borderRadius:20,padding:'7px 12px',background:'#ddd5ef'}}>{s}</span>)}</div><Img src={room} style={{position:'absolute',top:215,width:'100%',height:705,objectFit:'cover',filter:'grayscale(1)'}}/><div style={{position:'absolute',left:65,top:540,width:385,height:340,borderRadius:'50%',overflow:'hidden',boxShadow:'0 15px 30px #0005'}}>{pic()}</div></AbsoluteFill>;
 if(kind===1)return <AbsoluteFill style={{background:'#ededf0'}}>{heading}{['记录模式','回顾模式'].map((s,i)=><div key={i} style={{position:'absolute',left:20,right:20,top:140+i*374,height:358,background:i?'#ddd':'white',borderRadius:18,overflow:'hidden'}}><div style={{position:'absolute',left:20,top:20,fontSize:24,zIndex:1,border:`1px solid ${accent}`,borderRadius:24,padding:'5px 12px'}}>{s}</div><div style={{position:'absolute',left:75,top:35,width:340,height:320,transform:`rotate(${i?18:-10}deg)`}}>{pic({mixBlendMode:'multiply'})}</div>{i===1&&<svg width="474" height="358" style={{position:'absolute'}}><path d="M0 230 L20 200 L30 245 L45 183 L56 256 L70 198 L90 230 L115 202 L130 246 L150 210 L180 240 L220 215 L250 246 L275 215 L305 250 L340 205 L370 232 L400 199 L430 244 L474 218" fill="none" stroke={accent} strokeWidth={2}/></svg>}</div>)}</AbsoluteFill>;
 if(kind===3)return <AbsoluteFill style={{background:'#e9e8ed'}}>{heading}<div style={{position:'absolute',left:45,top:235,width:423,height:470}}>{pic({mixBlendMode:'multiply'})}</div><svg width="513" height="920" style={{position:'absolute'}}><ellipse cx={256} cy={460} rx={233} ry={125} fill="none" stroke={accent} strokeWidth={5}/><ellipse cx={256} cy={460} rx={170} ry={255} fill="none" stroke="#777" strokeWidth={2}/></svg><div style={{position:'absolute',top:790,left:70,right:70,textAlign:'center',fontSize:25}}>围绕你的表达，整理每个想法</div></AbsoluteFill>;
 if(kind===4)return <AbsoluteFill><Img src={room} style={{width:'100%',height:'100%',objectFit:'cover',filter:'grayscale(1)'}}/><div style={{position:'absolute',left:38,top:62,fontSize:44,fontWeight:900}}>随时留下灵感</div><div style={{position:'absolute',left:95,top:535,width:330,height:330,overflow:'hidden',borderRadius:'50%',boxShadow:'12px 20px 25px #0005'}}>{pic()}</div></AbsoluteFill>;
 return <AbsoluteFill style={{background:'#ededf0'}}>{heading}<div style={{position:'absolute',left:63,top:250,width:390,height:400}}>{pic({mixBlendMode:'multiply'})}</div>{['即时输入','清晰回看','灵感整理','内容输出'].map((s,i)=><div key={s} style={{position:'absolute',left:i%2?340:35,top:i<2?175:745,width:135,textAlign:'center',fontSize:23}}><div style={{fontSize:43,color:accent}}>{['◉','◎','▤','◈'][i]}</div>{s}</div>)}</AbsoluteFill>;
}
export function RebuiltX015({t,overrides={}}:{t:number;overrides?:Overrides}){
 const f=t*60,accent=overrides.accent??'#8554E8',w=overrides.words??[],product=staticFile(overrides.assets?.product??'group-a/fred-product.png'),room=staticFile(overrides.assets?.scene??'group-a/room.jpg');
 const wash=val(f,cues.exitWash);
 return <AbsoluteFill style={{background:'white',fontFamily:'MiSans',color:'#171719'}}>
  <AbsoluteFill style={{background:'#f4f4f7',padding:70,opacity:Math.max(0,Math.min(1,(f-374)/20))}}><div style={{fontSize:38,fontWeight:800}}>Fred · 创作素材</div><div style={{display:'flex',gap:30,marginTop:50}}>{Array.from({length:5},(_,i)=><div key={i} style={{position:'relative',width:290,height:600,background:'white',borderRadius:20,overflow:'hidden'}}><div style={{position:'absolute',left:0,top:0,width:513,height:918,transform:'scale(0.5653)',transformOrigin:'top left'}}><Poster kind={i} product={product} room={room} accent={accent} title="创作灵感"/></div></div>)}</div></AbsoluteFill>
  {[0,1,2].map(i=>{const local=f-i*30;if(local<0)return null;const x=[115.5,703.5,1291.5][i]+val(local,cues.offset)*1.5;return <div key={i} style={{position:'absolute',left:x,top:81,width:513,height:918,borderRadius:28,overflow:'hidden',boxShadow:'28px 13px 24px #0005',opacity:(i===0?1:Math.max(0,Math.min(1,local/14)))*(1-wash)}}><Poster kind={i} product={product} room={room} accent={accent} title={w[i]??['专注表达新体验','记录回顾 一键切换','四种创作方式'][i]}/>{i<2&&<AbsoluteFill style={{zIndex:3,opacity:val(f,i===0?cues.firstMix:cues.secondMix)}}><Poster kind={i===0?3:4} product={product} room={room} accent={accent} title={w[i+3]??['灵感随时捕捉','随时留下灵感'][i]}/></AbsoluteFill>}</div>})}
 </AbsoluteFill>;
}
