import {FiveFontFace} from "../../../five-fonts.ts";
import React,{useEffect,useState}from'react';
import{AbsoluteFill,staticFile,delayRender,continueRender,cancelRender}from'remotion';
import data from '../../../specs/B064.json';
import arrows from '../public/rebuilt-b064/arrow-paths.json';
import cursorPaths from '../public/rebuilt-b064/cursor-paths.json';
import{measured,type ClipSpec}from'../../../runtime/clip-spec';
export function RebuiltB064({frame,proof=false}:{frame:number;proof?:boolean}){
 const spec=data as unknown as ClipSpec;const win=data.objects.window;const [handle]=useState(()=>delayRender('B064 actual fonts'));const [metrics,setMetrics]=useState({hand:[130,130,130],title:160});
 useEffect(()=>{Promise.all(data.fonts.map(font=>new FiveFontFace(font.family,`url(${staticFile(font.file)})`,{weight:font.weight}).load().then(f=>document.fonts.add(f)))).then(()=>{const ctx=document.createElement('canvas').getContext('2d')!;ctx.font=`${data.fonts[0].fontSize}px ${data.fonts[0].family}`;const hand=(proof?data.content.referenceWords:data.content.words).map(w=>ctx.measureText(w).actualBoundingBoxAscent);ctx.font=`${data.fonts[1].fontSize}px ${data.fonts[1].family}`;setMetrics({hand,title:ctx.measureText(proof?data.content.referenceTitle:data.content.title).actualBoundingBoxAscent});continueRender(handle)}).catch(cancelRender)},[handle,proof]);
 const y=measured(spec,'window',frame)[0];const opacity=measured(spec,'opacity',frame);const blur=measured(spec,'blur',frame)[0];const [titleAlpha,titleScale,titleY]=measured(spec,'title',frame);const buttonAlpha=measured(spec,'button',frame)[0];const button=data.objects.button;const cursor=data.objects.cursor;const [cursorAlpha,cursorX,cursorY,cursorScale]=measured(spec,'cursor',frame);
 return <AbsoluteFill style={{background:'#fff',overflow:'hidden'}}><div style={{position:'absolute',inset:0,transform:`translateY(${y-win.stableY}px)`,filter:`blur(${blur}px)`}}><div style={{position:'absolute',left:win.left,top:win.stableY,width:win.width,height:win.height,background:win.fill,borderRadius:win.radius,boxShadow:win.shadow,overflow:'hidden'}}><div style={{height:win.headerHeight,background:win.headerFill}}/>{win.dots.map(([color,left],i)=><div key={i} style={{position:'absolute',left:Number(left)-11,top:33,width:22,height:22,borderRadius:'50%',background:String(color)}}/>)}</div><svg width={1920} height={1080} style={{position:'absolute',inset:0}}>{arrows.map((arrow,i)=><g key={i} opacity={opacity[i]}>{arrow.layers.map((layer,j)=><path key={j} d={layer.d} fill="white" opacity={layer.alpha}/>)}</g>)}{(proof?data.content.referenceWords:data.content.words).map((word,i)=><text key={i} x={i===2?data.objects.labels[i].leftAnchor:data.objects.labels[i].centerX} y={data.objects.labels[i].inkTop+metrics.hand[i]} textAnchor={i===2?"start":"middle"} opacity={opacity[i+3]} fill="white" style={{fontFamily:data.fonts[0].family,fontSize:data.fonts[0].fontSize,fontWeight:400,fontSynthesis:'none'}}>{word}</text>)}</svg><div style={{position:'absolute',left:button.left,top:button.top,width:button.width,height:button.height,borderRadius:button.radius,background:proof?'#54a5be':data.content.accent,opacity:buttonAlpha,display:'flex',alignItems:'center',justifyContent:'center',fontFamily:data.fonts[1].family,fontSize:button.fontSize,color:'white',fontWeight:400,fontSynthesis:'none'}}>{proof?data.content.referenceButton:data.content.button}</div><svg width={cursor.width} height={cursor.height} style={{position:'absolute',left:cursor.left+cursorX,top:cursor.top+cursorY,opacity:cursorAlpha,transform:`scale(${cursorScale})`,transformOrigin:'11px 12px'}}>{cursorPaths.map((layer,i)=><path key={i} d={layer.d} fill={layer.fill}/>)}</svg></div><svg width={1920} height={1080} style={{position:'absolute',inset:0,overflow:'visible'}}><g transform={`translate(960 ${titleY}) scale(${titleScale}) translate(-960 -540)`} opacity={titleAlpha}><text x={960} y={460+metrics.title} textAnchor="middle" fill={proof?'#d7ea70':data.content.accent} style={{fontFamily:data.fonts[1].family,fontSize:data.fonts[1].fontSize,fontWeight:400,fontSynthesis:'none',letterSpacing:data.fonts[1].letterSpacing,filter:'drop-shadow(5px 7px 4px #0008)'}}>{proof?data.content.referenceTitle:data.content.title}</text></g></svg></AbsoluteFill>
}
