import {RebuiltN003} from './RebuiltN003';
import {RebuiltN032} from './RebuiltN032';
import {RebuiltN037} from './RebuiltN037';
import {RebuiltX014} from './RebuiltX014';
import {RebuiltX015} from './RebuiltX015';
import {RebuiltX002} from './RebuiltX002';
import {RebuiltX008} from './RebuiltX008';
import {RebuiltX010} from './RebuiltX010';
import {RebuiltX006} from './RebuiltX006';
import {RebuiltX009} from './RebuiltX009';
import {RebuiltX003} from './RebuiltX003';
import {RebuiltN004} from './RebuiltN004';
import {RebuiltN007} from './RebuiltN007';
import {RebuiltN008} from './RebuiltN008';
import {RebuiltN005} from './RebuiltN005';
import {CalibratedN002,CalibratedN006} from './calibration-a';
import React,{CSSProperties} from 'react';
import type {Overrides} from './index';
import {AbsoluteFill,Img,OffthreadVideo,Sequence,Freeze,staticFile,interpolate,Easing} from 'remotion';

type Props={id:string;t:number;duration:number;overrides?:Overrides};
type Context={t:number;duration:number;accent:string;words:string[];assets:Record<string,string>;highlightWords?:string[];actorFraming?:Overrides['actorFraming']};
const INK='#171719';
const ease=Easing.bezier(.22,1,.36,1);
const p=(t:number,a:number,b:number)=>interpolate(t,[a,b],[0,1],{easing:ease,extrapolateLeft:'clamp',extrapolateRight:'clamp'});
const lin=(t:number,a:number,b:number)=>Math.min(1,Math.max(0,(t-a)/(b-a)));
const mix=(a:number,b:number,v:number)=>a+(b-a)*v;
const abs=(x:number,y:number,w?:number,h?:number):CSSProperties=>({position:'absolute',left:x,top:y,width:w,height:h});
const center:CSSProperties={display:'flex',alignItems:'center',justifyContent:'center'};
const shadow='0 16px 32px rgba(0,0,0,.13)';
const word=(c:Context,i:number,fallback:string)=>c.words[i]??fallback;
const media=(c:Context,key:string,fallback:string)=>staticFile(c.assets[key]??`group-a/${fallback}`);
const highlightedIndices=(text:string,terms:string[])=>{const chars=Array.from(text),marked=new Set<number>();for(const term of terms){const needle=Array.from(term);if(!needle.length)continue;for(let i=0;i<=chars.length-needle.length;i++)if(needle.every((v,j)=>chars[i+j]===v))for(let j=0;j<needle.length;j++)marked.add(i+j);}return marked;};
const type=(s:string,t:number,a:number,b:number)=>Array.from(s).slice(0,Math.floor(lin(t,a,b)*Array.from(s).length)).join('');
function Text({children,style={}}:{children:React.ReactNode;style?:CSSProperties}){return <div style={{fontWeight:700,lineHeight:1.25,...style}}>{children}</div>}
function Window({children,style={},dark=false}:{children:React.ReactNode;style?:CSSProperties;dark?:boolean}){return <div style={{background:dark?INK:'#fff',borderRadius:24,overflow:'hidden',boxShadow:shadow,...style}}><div style={{height:40,background:dark?'#242428':'#f1f1f4',display:'flex',alignItems:'center',gap:10,paddingLeft:24}}>{['#8554E8','#bbb','#ddd'].map((c,i)=><i key={i} style={{width:10,height:10,borderRadius:10,background:c}}/>)}</div>{children}</div>}
function ClipVideo({c,slot='video',file='scene-a.mp4',style={}}:{c:Context;slot?:string;file?:string;style?:CSSProperties}){return <OffthreadVideo muted src={media(c,slot,file)} style={{width:'100%',height:'100%',objectFit:'cover',...style}}/>}
function Sheet({accent,title='Fred 创作工作台'}:{accent:string;title?:string}){return <AbsoluteFill style={{background:'#f5f5f7',padding:44}}><div style={{fontSize:30,fontWeight:700,borderBottom:'1px solid #ddd',paddingBottom:22}}>{title}</div><div style={{display:'flex',gap:36,height:'90%',paddingTop:30}}><div style={{width:290,fontSize:25,color:'#777',lineHeight:2.8}}>项目空间<br/>视频素材<br/><span style={{color:accent}}>当前创作</span><br/>历史记录</div><div style={{background:'white',padding:48,flex:1,borderRadius:20}}><h2 style={{fontSize:42,margin:0}}>用清晰的表达，把想法变成作品</h2><p style={{fontSize:28,color:'#777'}}>描述你的目标，添加参考内容，开始创建。</p><div style={{border:'2px solid #ddd',height:160,borderRadius:20,padding:30,fontSize:25}}>为这次分享整理内容结构和视觉方案</div><div style={{display:'flex',gap:24,marginTop:38}}>{['文字内容','图片素材','视频片段'].map((v,i)=><div key={v} style={{flex:1,padding:26,background:i===0?'#eee8fb':'#f4f4f6',borderRadius:16,fontSize:27}}>{v}</div>)}</div><div style={{marginTop:50,fontSize:28}}>最近项目</div><div style={{display:'flex',gap:30,marginTop:25}}>{['思路整理','脚本打磨','镜头制作'].map(v=><div key={v} style={{height:190,flex:1,border:'1px solid #ddd',borderRadius:18,padding:24,fontSize:27}}>{v}</div>)}</div></div></div></AbsoluteFill>}

function QuestionQueue(c:Context){const starts=[.33,1.53,2.87,4.1,5.46];const labels=['换装视频能不能做','短剧视频能不能做','正能量视频能不能做','带货视频能不能做','口播视频能不能做'];return <AbsoluteFill>{labels.map((label,i)=>{const a=starts[i];if(c.t<a)return null;let shift=0;for(let k=i+1;k<starts.length;k++)shift+=p(c.t,starts[k],starts[k]+.34);const shown=type(word(c,i,label),c.t,a,a+.92);return <Text key={i} style={{...abs(90-mix(0,50,Math.min(1,shift)),460-240*shift),fontSize:136,whiteSpace:'nowrap',color:shift>0?'#79797d':INK,transform:`rotate(${-10*Math.min(1,shift)}deg)`,transformOrigin:'left center'}}>{shown}{c.t>a+.92&&<span style={{color:c.accent}}>？</span>}</Text>})}</AbsoluteFill>}
function QuestionWall(c:Context){const spread=p(c.t,1.1,1.85),answer=p(c.t,1.42,1.9);const qs=['只有参考图能不能做','正能量视频能不能做','啥参考都没有能不能做','母婴产品能不能做','口播视频能不能做'];return <AbsoluteFill>{qs.map((q,i)=><div key={q} style={{...abs(-420,75+i*176,2760,150),display:'flex',justifyContent:'center',gap:80,transform:`rotate(${mix(-8,0,p(c.t,0,.7))}deg)`,opacity:1-p(c.t,2.0,2.35)}}>{[-1,0,1].map((j)=><Text key={j} style={{fontSize:102,whiteSpace:'nowrap',transform:`translateX(${(j===0?(i%2?-1:1):j)*spread*1550}px)`}}>{word(c,i,q)}<span style={{color:c.accent}}>？</span></Text>)}</div>)}<div style={{...abs(0,380,1920,280),...center,gap:22,color:c.accent,fontSize:242,fontWeight:800,opacity:answer,transform:`translateY(${(1-answer)*90}px) scale(${mix(.85,1,answer)})`,filter:`blur(${(1-answer)*12}px)`}}>{Array.from(word(c,5,'都能做')).map((s,i)=><span key={i} style={{opacity:p(c.t,i===1?1.42:1.8,i===1?1.85:2.2)}}>{s}</span>)}</div></AbsoluteFill>}
function VideoRibbon(c:Context){const travel=p(c.t,1.28,1.68)+p(c.t,2.67,3.14);const settle=p(c.t,4.65,5.6);return <AbsoluteFill style={{perspective:1500}}>{[-1,0,1,2,3].map((j)=>{const d=j-travel;const focused=Math.max(0,1-Math.abs(d));return <div key={j} style={{...abs(960+d*1370-660,180,1320,742),transform:`perspective(1600px) rotateY(${-Math.max(-1,Math.min(1,d))*24}deg) scale(${.90+.1*focused+.045*settle*focused})`,borderRadius:40,overflow:'hidden',boxShadow:shadow,opacity:j===2?1:1-settle*.85}}><ClipVideo c={c} slot={`video${j+1}`} file={j%2?'scene-b.mp4':'scene-a.mp4'}/></div>})}</AbsoluteFill>}
const abilities=['可直出 1080p 高清视频','清晰呈现中文文字','支持图片、音频与视频参考'];
function AbilityList(c:Context,check:boolean){const shrink=check?p(c.t,0,.72):0;return <Window dark style={{...abs(105,75,1710,915),borderRadius:62}}><div style={{padding:'68px 72px'}}>{abilities.map((s,i)=>{const a=check?0:[-1,.2,3.55][i],enter=check?1:p(c.t,a,a+.48),tick=check?p(c.t,[2.05,1.4,.7][i],[2.4,1.75,1.05][i]):0;return <div key={i} style={{position:'relative',height:260,display:'flex',alignItems:'center',color:'#fff',opacity:enter,transform:`translateY(${(1-enter)*32}px)`}}><Text style={{fontSize:(i===2?87:110)*mix(1,.88,shrink),letterSpacing:-2,whiteSpace:'nowrap'}}><span style={{color:c.accent}}>{i+1}.</span>{word(c,i,s)}</Text>{check&&<div style={{position:'absolute',right:0,width:100,height:100,...center}}><svg width="90" height="90" viewBox="0 0 100 100"><circle cx="50" cy="50" r={7*(1-tick)} fill={c.accent}/><path d="M20 51 L42 72 L81 28" pathLength="1" stroke={c.accent} strokeWidth="13" fill="none" strokeLinecap="round" strokeLinejoin="round" strokeDasharray="1" strokeDashoffset={1-tick}/></svg></div>}</div>})}</div></Window>}
function Chapter(c:Context){const gather=p(c.t,0,1.65),take=p(c.t,2.8,3.35),anchor=p(c.t,3.65,4.1),inverse=p(c.t,5.6,6.6);const body=word(c,1,'在这段提示词中，用 @素材 的方式，锁住人物样貌、场景画风、人物动作，以及说话音色、拍摄运镜等参考信息。');const txt=type(body,c.t,4.35,6.55);const highlights=c.highlightWords??(c.words[1]!==undefined?['@素材','人物造型','环境光线','动作顺序','声音节奏','画面构图']:undefined);const marked=highlights?highlightedIndices(body,highlights):undefined;return <AbsoluteFill><div style={{opacity:1-take,filter:'blur(5px)'}}><Sheet accent={c.accent}/></div>{Array.from({length:6},(_,i)=>{const e=p(c.t,i*.21,i*.21+.62);const x=140+(i%3)*570,y=90+Math.floor(i/3)*470;return <div key={i} style={{...abs(mix(850,x,e),mix(430,y,e),mix(220,500,e),mix(220,400,e)),borderRadius:mix(110,62,e),background:INK,opacity:1-take,boxShadow:shadow}}/>})}<div style={{...abs(mix(140,0,take),mix(90,0,take),mix(500,1920,take),mix(400,1080,take)),background:`rgb(${Math.round(mix(23,255,inverse))},${Math.round(mix(23,255,inverse))},${Math.round(mix(25,255,inverse))})`,borderRadius:mix(62,0,take),opacity:take}}/><Text style={{...abs(mix(700,80,anchor),mix(455,54,anchor)),color:c.accent,fontSize:mix(150,68,anchor),opacity:p(c.t,2.92,3.3),whiteSpace:'nowrap'}}>{word(c,0,'一、定义')}</Text><Text style={{...abs(100,280,1720),fontSize:88,color:inverse>.52?INK:'#fff',lineHeight:1.5,opacity:p(c.t,4.3,4.5)}}>{Array.from(txt).map((s,i)=><span key={i} style={{color:inverse>.7&&(marked?marked.has(i):((i>=11&&i<14)||(i>=20&&i<24)||(i>=43&&i<47)))?c.accent:undefined}}>{s}</span>)}</Text></AbsoluteFill>}
function Example(c:Context,constraint:boolean){const exit=p(c.t,.35,.95),enter=p(c.t,.62,1.2);const desc=constraint?'在这段提示词中明确写清楚：哪些东西不能变，以及避免人物失真、穿模、画面闪烁的控制要求。':'在这段提示词中概括描述整段视频的时长和大致内容，也可以补充画面风格以及画质氛围等附加信息。';const example=constraint?'@人物1：保持五官、发型和服装与参考图一致，不得改变。\n@人物2：保留毛色和体型，去掉红色项圈。\n@场景1：保持沙发颜色、材质与客厅布局。\n@音频1：完整使用原音频，口型和动作节奏跟随音频。':'生成一支10秒的实拍风格短片：@人物1 坐在 @场景1 的沙发上，@人物2 趴在她身旁，她跟着 @音频1 唱歌。\n整体为电影感实拍画面，暖色自然光，画质细腻，氛围温馨放松。';return <AbsoluteFill><Text style={{...abs(60,42),fontSize:68,color:c.accent}}>{word(c,0,constraint?'三、约束':'二、摘要')}</Text><Text style={{...abs(90,270,1740),fontSize:98,lineHeight:1.42,opacity:1-exit,filter:`blur(${exit*5}px)`}}>{word(c,1,desc)}</Text><div style={{...abs(65,mix(1120,constraint?228:700,enter),1790,constraint?650:325),background:INK,borderRadius:68,padding:'48px 52px',boxSizing:'border-box',boxShadow:shadow}}><div style={{fontSize:constraint?47:48,lineHeight:1.6,color:'#fff',whiteSpace:'pre-line',opacity:p(c.t,.95,1.45)}}>{word(c,2,example)}</div></div></AbsoluteFill>}
function ProductRoles(c:Context){const win=p(c.t,.8,1.22),exit=p(c.t,4,4.3),results=p(c.t,6.4,7.15);return <AbsoluteFill><div style={{...abs(150,230,570,600),opacity:1-results,transform:`scale(${1-results*.1})`}}><Img src={media(c,'product','product.jpg')} style={{width:'100%',height:'100%',objectFit:'contain',mixBlendMode:'multiply'}}/></div><Window dark style={{...abs(mix(2040,915,win),100,825,875),opacity:1-exit}}><div style={{padding:'70px 70px'}}>{['卖给谁？','在哪卖？','卖点是？'].map((s,i)=><Text key={i} style={{fontSize:116,marginBottom:90,color:i===0?'#fff':c.accent,opacity:p(c.t,[1.2,2.1,2.85][i],[1.5,2.4,3.15][i])}}>{word(c,i,s)}</Text>)}</div></Window><div style={{...abs(825,270,975,560),opacity:(1-results)*exit}}>{['市场研究员','文案师','设计师'].map((s,i)=><Text key={s} style={{position:'absolute',top:i===0?0:340,left:i===2?550:30,fontSize:112,color:i===0?INK:c.accent,opacity:p(c.t,4.4+i*.5,4.75+i*.5),transform:`translateY(${(1-p(c.t,4.4+i*.5,4.75+i*.5))*60}px)`}}>{word(c,i+3,s)}</Text>)}</div>{['product.jpg','shoe.jpg','perfume.jpg','car.jpg'].map((file,i)=><div key={file} style={{...abs(320+(i%2)*730,70+Math.floor(i/2)*490,560,450),borderRadius:24,overflow:'hidden',boxShadow:shadow,opacity:p(c.t,6.3+i*.14,6.85+i*.14),transform:`scale(${mix(.8,1,results)})`}}><Img src={media(c,`result${i}`,file)} style={{width:'100%',height:'100%',objectFit:'cover'}}/></div>)}</AbsoluteFill>}
function AnswerPerson(c:Context){const shrink=p(c.t,0,.4),shift=p(c.t,2.43,3.2),answer=p(c.t,2.43,2.58),width=mix(1580,320,shrink);return <AbsoluteFill><div style={{...abs(mix(170,800,shrink)-shift*400,375,width,320),borderRadius:160,background:INK,boxShadow:shadow,...center,overflow:'hidden',zIndex:2}}><Text style={{position:'absolute',color:c.accent,fontSize:Math.min(128,(width-100)*.086),whiteSpace:'nowrap',opacity:1-p(c.t,0,.18)}}>{word(c,0,'8G 显存 + 量化模型')}</Text><Text style={{position:'absolute',color:c.accent,fontSize:176,opacity:p(c.t,.13,.3)*(1-answer)}}>？</Text><Text style={{position:'absolute',color:c.accent,fontSize:176,opacity:answer}}>{word(c,1,'能')}</Text></div><Sequence from={138}><div style={{...abs(mix(1800,760,p(c.t,2.3,2.9)),140,1000,1000)}}><Freeze frame={Math.min(108,Math.max(0,Math.round((c.t-2.3)*60)))}><OffthreadVideo startFrom={120} transparent muted src={media(c,'actor','actor-show.webm')} style={{width:'100%',height:'100%',objectFit:'contain',transform:'scaleX(-1)'}}/></Freeze></div></Sequence></AbsoluteFill>}
function Burst({t,start,x,y,r=130,color}:{t:number;start:number;x:number;y:number;r?:number;color:string}){if(t<start)return null;const a=lin(t,start,start+.42);return <svg style={{...abs(x-r*1.8,y-r*1.8,r*3.6,r*3.6),overflow:'visible',opacity:1-a}} viewBox="-180 -180 360 360">{Array.from({length:12},(_,i)=>{const ang=i*Math.PI/6;return <line key={i} x1={Math.cos(ang)*(100+a*30)} y1={Math.sin(ang)*(100+a*30)} x2={Math.cos(ang)*(110+a*60)} y2={Math.sin(ang)*(110+a*60)} stroke={color} strokeWidth={4*(1-a)} strokeLinecap="round"/>})}</svg>}
function Actions(c:Context){return <AbsoluteFill><div style={{filter:`blur(${p(c.t,0,.25)*9}px)`,opacity:.42}}><Sheet accent={c.accent}/></div><div style={{...abs(795,190,330,330),border:'8px solid #fff',borderRadius:'50%',background:INK,boxShadow:shadow,overflow:'hidden',transform:`scale(${mix(.25,1,p(c.t,0,.25))})`}}><OffthreadVideo transparent muted src={media(c,'actor','actor.webm')} style={{width:590*(c.actorFraming?.scale??1),height:590*(c.actorFraming?.scale??1),position:'absolute',left:-135+(c.actorFraming?.x??0),top:c.actorFraming?.y??0,objectFit:'contain'}}/></div><Burst t={c.t} start={.35} x={960} y={355} color={c.accent}/>{[0,1,2].map(i=>{const a=.75+i*.33,enter=p(c.t,a,a+.24),x=460+i*500;return <React.Fragment key={i}><div style={{...abs(x-90,720,180,180),transform:`scale(${enter+.14*Math.sin(Math.PI*enter)})`,opacity:enter,color:c.accent}}><svg viewBox="0 0 100 100" fill="currentColor">{i===0?<path d="M12 44h17v43H12zm23 0 20-30c9-5 13 0 10 11l-4 18h20c9 0 12 6 10 14l-7 24c-1 4-6 6-10 6H35z"/>:i===1?<path d="M10 78c3-28 17-41 44-42V14l37 34-37 33V59C33 58 20 65 10 78z"/>:<path d="m50 8 13 26 29 4-21 21 5 29-26-14-26 14 5-29L8 38l29-4z"/>}</svg></div><Burst t={c.t} start={a+.12} x={x} y={810} r={80} color={c.accent}/></React.Fragment>})}</AbsoluteFill>}
function VideoWall(c:Context){const grid=[[70,75,380,650],[490,75,720,440],[1250,75,600,205],[1250,320,600,205],[70,765,380,245],[490,555,370,455],[900,555,310,455],[1250,565,600,445]];return <AbsoluteFill>{grid.map(([x,y,w,h],i)=>{const a=.55+i*.075,e=p(c.t,a,a+.55);return <div key={i} style={{...abs(x,y+(1-e)*(i%2?-400:600),w,h),opacity:e,borderRadius:28,overflow:'hidden',boxShadow:shadow}}><ClipVideo c={c} slot={`video${i}`} file={i%2?'scene-b.mp4':'scene-a.mp4'} style={{transform:`scale(${1+.03*(1+Math.sin(i))})`}}/></div>})}<div style={{...abs(0,0,1920,1080),...center,gap:300,opacity:1-p(c.t,.2,.6),background:'rgba(255,255,255,.8)'}}>{['算力','显存'].map((s,i)=><Text key={s} style={{fontSize:150,padding:'36px 75px',borderRadius:38,background:i===0?c.accent:INK,color:'white'}}>{word(c,i,s)}</Text>)}</div></AbsoluteFill>}
function ConditionCapsule(c:Context){const open=p(c.t,0,.8),extend=p(c.t,3.8,4.65),s=word(c,0,'8G 显存笔记本'),tail=word(c,1,' + 量化模型');return <AbsoluteFill><div style={{...abs(960-mix(115,580+280*extend,open),540-mix(115,175-35*extend,open),mix(230,1160+560*extend,open),mix(230,350-70*extend,open)),borderRadius:mix(115,90,open),background:INK,boxShadow:shadow,...center,overflow:'hidden'}}><Text style={{fontSize:mix(140,116,extend),color:'#fff',whiteSpace:'nowrap'}}>{type(s,c.t,1.25,2.1)}<span style={{color:c.accent}}>{type(tail,c.t,4,4.7)}</span></Text></div></AbsoluteFill>}
function GenerationList(c:Context){const fade=1-p(c.t,5.35,6);return <AbsoluteFill><div style={{filter:'blur(9px)',opacity:.2}}><Sheet accent={c.accent} title="Fred 视频制作流程"/></div><div style={{...abs(235,175,1480,760),opacity:fade}}>{['文生视频','图生视频','参考图生视频'].map((s,i)=><div key={i} style={{height:245,display:'flex',alignItems:'center'}}><Text style={{fontSize:144,color:c.accent,width:275}}>{i+1}、</Text><Text style={{fontSize:136,whiteSpace:'nowrap'}}>{type(word(c,i,s),c.t,[1.6,2.35,3.18][i],[1.95,2.75,3.65][i])}</Text></div>)}</div></AbsoluteFill>}
function DoubleCapsule(c:Context){const first=p(c.t,1.4,2.1),lift=p(c.t,4,5.45),second=p(c.t,6.3,7.05),merge=p(c.t,9.1,10);return <AbsoluteFill><div style={{opacity:1-p(c.t,0,1.1)}}><Sheet accent={c.accent}/></div><div style={{...abs(960-mix(150,600,first)*mix(1,.8,lift),mix(385,90,lift),mix(300,1200,first)*mix(1,.8,lift),mix(310,235,lift)),borderRadius:mix(160,90,first),opacity:p(c.t,1.35,1.55),background:INK,...center,boxShadow:shadow}}><Text style={{fontSize:mix(142,118,lift),color:'#fff',opacity:p(c.t,2,2.5)*(1-merge)}}>{word(c,0,'提示词怎么写')}</Text></div><div style={{...abs(mix(500,105,merge),mix(370,70,merge),mix(920,1710,merge)+420*second*(1-merge),mix(280,925,merge)),transform:`translateX(${-210*second*(1-merge)}px)`,background:INK,borderRadius:65,opacity:second,...center,boxShadow:shadow}}><Text style={{fontSize:145,color:c.accent,opacity:p(c.t,7,7.65)*(1-merge)}}>{word(c,1,'模型的基础能力')}</Text></div></AbsoluteFill>}
function Report(c:Context){const focus=p(c.t,.7,1.25),back=p(c.t,3.05,3.65),scroll=p(c.t,3.8,5.85);const activity=<><div style={{fontSize:38,fontWeight:700,marginBottom:34}}>Fred 创作助手</div><div style={{fontSize:30,color:'#666',marginBottom:36}}>我为你组建了一个创作团队：</div>{['市场研究员 · 分析目标用户','内容策划 · 明确传播重点','视觉设计师 · 整理图片方案'].map((s,i)=><div key={s} style={{marginTop:28,fontSize:29,color:i===0?c.accent:INK}}>{s}</div>)}<div style={{fontSize:27,color:'#999',marginTop:36}}>正在生成完整报告…</div></>;return <AbsoluteFill><div style={{filter:`blur(${focus*(1-back)*8}px)`}}><Sheet accent={c.accent} title="Fred · 创作研究"/></div><div style={{...abs(mix(65,600,focus)*(1-back)+65*back,mix(370,240,focus)*(1-back)+370*back,mix(380,720,focus)*(1-back)+380*back,mix(460,620,focus)*(1-back)+460*back),padding:34,boxSizing:'border-box',background:'#fff',borderRadius:24,boxShadow:focus*(1-back)>.1?shadow:'none',transformOrigin:'top left',fontSize:26}}><div style={{transform:`scale(${mix(.48,1,focus)*(1-back)+.48*back})`,transformOrigin:'top left',width:650}}>{activity}</div></div><div style={{...abs(560,150,1210,850),borderRadius:28,background:'white',padding:60,boxSizing:'border-box',overflow:'hidden',boxShadow:shadow,opacity:back}}><div style={{transform:`translateY(${-scroll*620}px)`}}><Text style={{fontSize:49}}>{word(c,0,'产品创意 · 用户研究报告')}</Text><div style={{fontSize:30,lineHeight:1.85,marginTop:46}}>{['研究目标','用户画像','需求与动机','内容策略','视觉建议','下一步行动'].map((s,i)=><section key={s} style={{marginBottom:40}}><Text style={{fontSize:34,color:c.accent,marginBottom:16}}>{i+1}. {s}</Text><div>围绕实际使用场景，整理用户最关心的问题。</div><div>用真实产品信息支持结论，让表达清楚、具体。</div><div>将研究结果转化为可执行的内容与视觉方案。</div></section>)}</div></div></div></AbsoluteFill>}
function ProductCards(c:Context){const replacement=p(c.t,2.3,2.8),replacement2=p(c.t,3.35,3.9),out=p(c.t,6,6.7);const files=['product.jpg','portrait.jpg','perfume.jpg'];return <AbsoluteFill>{files.map((file,i)=>{const e=p(c.t,i*.5,i*.5+.45);return <div key={i} style={{...abs(115+i*595,80,510,900),opacity:e*(1-out),transform:`translateY(${(1-e)*180}px) scale(${1-out*.1})`,borderRadius:22,overflow:'hidden',boxShadow:shadow,background:'#f4f4f5'}}><Text style={{fontSize:43,textAlign:'center',padding:'42px 10px 25px'}}>{word(c,i,['沉浸式新体验','为灵感留出空间','细节成就质感'][i])}</Text><div style={{height:745,position:'relative'}}><Img src={media(c,`image${i}`,file)} style={{width:'100%',height:'100%',objectFit:'cover'}}/>{i<2&&<Img src={media(c,`replacement${i}`,i===0?'shoe.jpg':'room.jpg')} style={{position:'absolute',inset:0,width:'100%',height:'100%',objectFit:'cover',opacity:i===0?replacement:replacement2}}/>}</div></div>})}<div style={{opacity:out}}><Sheet accent={c.accent}/></div></AbsoluteFill>}
export function BatchA({id,t,duration,overrides={}}:Props){const c:Context={t,duration,accent:overrides.accent??'#8554E8',words:overrides.words??[],assets:overrides.assets??{},highlightWords:overrides.highlightWords,actorFraming:overrides.actorFraming};switch(id){case'N002':return <CalibratedN002 t={t} overrides={overrides}/>;case'N003':return <RebuiltN003 t={t} overrides={overrides}/>;case'N004':return <RebuiltN004 t={t} overrides={overrides}/>;case'N005':return <RebuiltN005 t={t} overrides={overrides}/>;case'N006':return <CalibratedN006 t={t} overrides={overrides}/>;case'N007':return <RebuiltN007 t={t} overrides={overrides}/>;case'N008':return <RebuiltN008 t={t} overrides={overrides}/>;case'N032':return <RebuiltN032 t={t} overrides={overrides}/>;case'N037':return <RebuiltN037 t={t} overrides={overrides}/>;case'X002':return <RebuiltX002 t={t} overrides={overrides}/>;case'X003':return <RebuiltX003 t={t} overrides={overrides}/>;case'X006':return <RebuiltX006 t={t} overrides={overrides}/>;case'X008':return <RebuiltX008 t={t} overrides={overrides}/>;case'X009':return <RebuiltX009 t={t} overrides={overrides}/>;case'X010':return <RebuiltX010 t={t} overrides={overrides}/>;case'X014':return <RebuiltX014 t={t} overrides={overrides}/>;case'X015':return <RebuiltX015 t={t} overrides={overrides}/>;default:throw new Error(`Batch A does not own ${id}`)}}
