import {DARK_PURPLE,purpleOnDark,purpleOnSurface} from "../surface-purple.ts";
import React from 'react';
import {AbsoluteFill,interpolate} from 'remotion';
import type {Overrides} from './index';
import cues from './timelines/X014.json';
const val=(f:number,p:number[][],col=1)=>interpolate(f,p.map(v=>v[0]),p.map(v=>v[col]),{extrapolateLeft:'clamp',extrapolateRight:'clamp'});
const ramp=(f:number,a:number,b:number)=>Math.max(0,Math.min(1,(f-a)/(b-a)));
function Team({accent}:{accent:string}){return <><div style={{display:'flex',alignItems:'center',gap:12,fontSize:29,fontWeight:800}}><span style={{width:40,height:40,borderRadius:30,background:'#111',color:purpleOnDark(accent),textAlign:'center'}}>✦</span>Fred 创作室</div><div style={{display:'inline-block',marginTop:28,padding:'12px 16px',borderRadius:30,background:'#f4f4f4',fontSize:24,color:'#999'}}>⌕ 读取产品内容与视觉创作要求</div><div style={{fontSize:27,margin:'40px 18px 26px'}}>我为你组建了一个创作团队：</div><div style={{marginLeft:20}}>{[['市场研究员','通过真实使用场景，整理用户需求与反馈'],['内容策划师','围绕产品的特点，写清楚内容和表达重点'],['视觉设计师','统一封面、图片与视频中的视觉语言']].map(([title,desc],i)=><div key={title} style={{position:'relative',height:85,borderLeft:'3px solid #ddd',paddingLeft:30}}><div style={{position:'absolute',left:0,top:36,width:20,borderTop:'3px solid #ddd'}}/><div style={{fontSize:24,color:accent}}><span style={{display:'inline-block',width:24,height:24,marginRight:12,background:i===1?'#333':accent,borderRadius:i===2?3:20}}/>@{title}</div><div style={{fontSize:22,color:'#aaa',marginTop:13,whiteSpace:'nowrap'}}>{desc}</div></div>)}</div><div style={{fontSize:28,fontWeight:700,color:'#999',marginTop:33}}>◌　思考中…</div></>}
export function RebuiltX014({t,overrides={}}:{t:number;overrides?:Overrides}){
 const f=t*60,accent=overrides.accent??'#8554E8',focus=ramp(f,45,66)*(1-ramp(f,188,201)),report=ramp(f,203,224),scroll=val(f,cues.scroll),box=cues.focusBox;
 const title=overrides.words?.[0]??'随身记录设备 · 用户与内容研究报告';
 return <AbsoluteFill style={{background:'#f4f7f8',fontFamily:'MiSans',color:'#222'}}>
 <AbsoluteFill style={{filter:`blur(${focus*10}px)`}}><div style={{position:'absolute',left:0,top:0,width:459,height:1080,background:'white',borderRight:'1px solid #ddd',padding:20,boxSizing:'border-box'}}><div style={{fontSize:23,fontWeight:800}}>✦ Fred 创作室 <span style={{fontSize:15,color:'#888',marginLeft:30}}>资料 · 画布 · 记录</span></div><div style={{background:'#eee9fa',borderRadius:12,marginTop:45,marginLeft:36,padding:24,fontSize:19,lineHeight:1.55}}>▧ 产品参考资料<div style={{marginTop:15}}>请围绕随身记录设备完成用户研究、内容策划和视觉设计。整理实际使用场景，说明目标用户的需求，并将产品特点转化为清楚、具体的表达。</div><div style={{marginTop:15}}>请先组建团队，再输出可以继续编辑的研究报告。</div></div><div style={{position:'absolute',left:20,bottom:25,right:20,height:125,border:'1px solid #eee',borderRadius:20,padding:16,fontSize:16,color:'#888'}}>继续补充你的想法<div style={{marginTop:55}}>＋　素材　　设置<span style={{float:'right',color:'#111'}}>●</span></div></div></div><div style={{position:'absolute',top:25,left:555,fontSize:20,color:'#888',opacity:report}}>◉ 创作研究报告　　编辑　　导出</div></AbsoluteFill>
 <div style={{position:'absolute',left:val(f,box,1),top:val(f,box,2),width:708,height:612,background:'white',borderRadius:26,padding:'12px 16px',boxSizing:'border-box',transform:`scale(${val(f,box,3)/708},${val(f,box,4)/612})`,transformOrigin:'top left',boxShadow:focus>.02?`${30*focus}px ${22*focus}px ${18*focus}px #0005`:'none'}}><Team accent={accent}/></div>
 <div style={{position:'absolute',left:546,top:111,width:1095,height:882,background:'white',border:'1px solid #dee3e5',borderRadius:28,overflow:'hidden',opacity:report}}><div style={{position:'absolute',top:32-scroll,left:40,right:48,fontSize:22,lineHeight:1.9}}><div style={{fontSize:35,fontWeight:800,marginBottom:24}}>{title}</div><div style={{fontSize:19,color:'#777',marginBottom:22}}>研究目标：从真实使用场景出发，建立清晰的产品表达。</div>{['需求洞察','目标用户与使用习惯','内容表达建议','产品图片与视频规划','执行步骤与检查要点'].map((s,i)=><section key={s} style={{marginBottom:30}}><div style={{fontSize:26,fontWeight:800,marginBottom:15}}>{i+1}. {s}</div>{['围绕日常记录、会议回顾与灵感整理，识别高频使用时刻。','把功能与用户需求对应起来，用具体场景解释产品价值。','保持文字、图片和视频的一致性，让信息能够连续传递。'].map((line,j)=><div key={j} style={{margin:'12px 0'}}><span style={{color:accent}}>▪ </span><b>{['使用场景','内容重点','交付建议'][j]}：</b>{line}</div>)}</section>)}</div><div style={{position:'absolute',right:8,top:70+scroll*.36,width:5,height:112,borderRadius:4,background:'#bbb'}}/></div>
 <svg width="25" height="33" style={{position:'absolute',left:1619,top:val(f,[[200,215],[222,270],[268,270],[300,295],[359,338]]),opacity:report}}><path d="M2 1 L3 24 L9 19 L14 29 L19 26 L14 17 L22 16 Z" fill="white" stroke="#555" strokeWidth="1.5"/></svg>
 </AbsoluteFill>;
}
